///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EasternBankRegression.Module_Recordings.MajorModules.SettingsTab.DefaultAccount
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DefaultBillPayAccount recording.
    /// </summary>
    [TestModule("af8d93ad-95d0-40ec-a0fe-aac568501326", ModuleType.Recording, 1)]
    public partial class DefaultBillPayAccount : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EasternBankRegression.EasternBankRegressionRepository repository.
        /// </summary>
        public static global::EasternBankRegression.EasternBankRegressionRepository repo = global::EasternBankRegression.EasternBankRegressionRepository.Instance;

        static DefaultBillPayAccount instance = new DefaultBillPayAccount();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DefaultBillPayAccount()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DefaultBillPayAccount Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.MajorModules.Settings_Sub.DefaultAccount.Validate1SELECTINTERESTCHECKINGACCT'", repo.ApplicationUnderTest.MajorModules.Settings_Sub.DefaultAccount.Validate1SELECTINTERESTCHECKINGACCTInfo, new ActionTimeout(30000), new RecordItemIndex(0));
            repo.ApplicationUnderTest.MajorModules.Settings_Sub.DefaultAccount.Validate1SELECTINTERESTCHECKINGACCTInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MajorModules.Settings_Sub.DefaultAccount.Validate1SELECTINTERESTCHECKINGACCT' at Center.", repo.ApplicationUnderTest.MajorModules.Settings_Sub.DefaultAccount.Validate1SELECTINTERESTCHECKINGACCTInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.MajorModules.Settings_Sub.DefaultAccount.Validate1SELECTINTERESTCHECKINGACCT.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
