///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Transfersv2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PrincipalOnlySuccess recording.
    /// </summary>
    [TestModule("89bce23b-2706-4f02-9d9a-f26bd719b25b", ModuleType.Recording, 1)]
    public partial class PrincipalOnlySuccess : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TransfersRepository repository.
        /// </summary>
        public static TransfersRepository repo = TransfersRepository.Instance;

        static PrincipalOnlySuccess instance = new PrincipalOnlySuccess();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PrincipalOnlySuccess()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PrincipalOnlySuccess Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varAccount.
        /// </summary>
        [TestVariable("a2d01dad-19ce-4358-9a5d-c6e79fa94c83")]
        public string varAccount
        {
            get { return repo.varAccount; }
            set { repo.varAccount = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varToLoanAccount.
        /// </summary>
        [TestVariable("25c97dae-9c8d-4c53-9737-9e7c15e99335")]
        public string varToLoanAccount
        {
            get { return repo.varToLoanAccount; }
            set { repo.varToLoanAccount = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InternalTransferModal.TransferFromDropdown'.", repo.EasternOnlineBankingDashboard.InternalTransferModal.TransferFromDropdownInfo, new RecordItemIndex(0));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.TransferFromDropdown.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InternalTransferModal.FromAccountList.varFromAccount'.", repo.EasternOnlineBankingDashboard.InternalTransferModal.FromAccountList.varFromAccountInfo, new RecordItemIndex(1));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.FromAccountList.varFromAccount.As<WebElement>().PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InternalTransferModal.TransferToDropdown'.", repo.EasternOnlineBankingDashboard.InternalTransferModal.TransferToDropdownInfo, new RecordItemIndex(2));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.TransferToDropdown.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InternalTransferModal.ToAccountList.varToLoanAccount'.", repo.EasternOnlineBankingDashboard.InternalTransferModal.ToAccountList.varToLoanAccountInfo, new RecordItemIndex(3));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.ToAccountList.varToLoanAccount.Element.InvokeActionWithText("PerformClick");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InternalTransferModal.TransferAmountInputBox'.", repo.EasternOnlineBankingDashboard.InternalTransferModal.TransferAmountInputBoxInfo, new RecordItemIndex(4));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.TransferAmountInputBox.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '5.00' with focus on 'EasternOnlineBankingDashboard.InternalTransferModal.TransferAmountInputBox'.", repo.EasternOnlineBankingDashboard.InternalTransferModal.TransferAmountInputBoxInfo, new RecordItemIndex(5));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.TransferAmountInputBox.PressKeys("5.00");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InternalTransferModal.LoanPaymentTypeDropdown'.", repo.EasternOnlineBankingDashboard.InternalTransferModal.LoanPaymentTypeDropdownInfo, new RecordItemIndex(6));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.LoanPaymentTypeDropdown.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InternalTransferModal.LoanPaymentTypeList.PrincipalOnly'.", repo.EasternOnlineBankingDashboard.InternalTransferModal.LoanPaymentTypeList.PrincipalOnlyInfo, new RecordItemIndex(7));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.LoanPaymentTypeList.PrincipalOnly.As<WebElement>().PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InternalTransferModal.ContinueButton'.", repo.EasternOnlineBankingDashboard.InternalTransferModal.ContinueButtonInfo, new RecordItemIndex(8));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.ContinueButton.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Valid' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.ConfirmTransferDetailsModal'", repo.EasternOnlineBankingDashboard.ConfirmTransferDetailsModal.SelfInfo, new RecordItemIndex(9));
            repo.EasternOnlineBankingDashboard.ConfirmTransferDetailsModal.SelfInfo.WaitForAttributeEqual(5000, "Valid", "True");
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.ConfirmTransferDetailsModal.ConfirmButton'.", repo.EasternOnlineBankingDashboard.ConfirmTransferDetailsModal.ConfirmButtonInfo, new RecordItemIndex(10));
            repo.EasternOnlineBankingDashboard.ConfirmTransferDetailsModal.ConfirmButton.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.TransferSuccessfulModal'", repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.SelfInfo, new RecordItemIndex(11));
            repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.SelfInfo.WaitForAttributeEqual(30000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.TransferSuccessfulModal.PrintButton'.", repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.PrintButtonInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.PrintButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.TransferSuccessfulModal.DoneButton'.", repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.DoneButtonInfo, new RecordItemIndex(13));
            repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.DoneButton.PerformClick();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
