///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RanorexAutomationHelpers
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RanorexAutomationHelpersRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("751ae5f2-b549-4f9b-ad7a-2afea234e318")]
    public partial class RanorexAutomationHelpersRepository : RepoGenBaseFolder
    {
        static RanorexAutomationHelpersRepository instance = new RanorexAutomationHelpersRepository();

        /// <summary>
        /// Gets the singleton class instance representing the RanorexAutomationHelpersRepository element repository.
        /// </summary>
        [RepositoryFolder("751ae5f2-b549-4f9b-ad7a-2afea234e318")]
        public static RanorexAutomationHelpersRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RanorexAutomationHelpersRepository() 
            : base("RanorexAutomationHelpersRepository", "/", null, 0, false, "751ae5f2-b549-4f9b-ad7a-2afea234e318", ".\\RepositoryImages\\RanorexAutomationHelpersRepository751ae5f2.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("751ae5f2-b549-4f9b-ad7a-2afea234e318")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class RanorexAutomationHelpersRepositoryFolders
    {
    }
#pragma warning restore 0436
}