///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Support_V2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SupportRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("5f1a29e8-c243-4169-8f5d-bedd5ec9655a")]
    public partial class SupportRepository : RepoGenBaseFolder
    {
        static SupportRepository instance = new SupportRepository();
        SupportRepositoryFolders.EasternOnlineBankingDashboardAppFolder _easternonlinebankingdashboard;

        /// <summary>
        /// Gets the singleton class instance representing the SupportRepository element repository.
        /// </summary>
        [RepositoryFolder("5f1a29e8-c243-4169-8f5d-bedd5ec9655a")]
        public static SupportRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SupportRepository() 
            : base("SupportRepository", "/", null, 0, false, "5f1a29e8-c243-4169-8f5d-bedd5ec9655a", ".\\RepositoryImages\\SupportRepository5f1a29e8.rximgres")
        {
            _easternonlinebankingdashboard = new SupportRepositoryFolders.EasternOnlineBankingDashboardAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5f1a29e8-c243-4169-8f5d-bedd5ec9655a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The EasternOnlineBankingDashboard folder.
        /// </summary>
        [RepositoryFolder("e104cb91-fc1f-43a9-b07b-f4d65a9dd567")]
        public virtual SupportRepositoryFolders.EasternOnlineBankingDashboardAppFolder EasternOnlineBankingDashboard
        {
            get { return _easternonlinebankingdashboard; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SupportRepositoryFolders
    {
        /// <summary>
        /// The EasternOnlineBankingDashboardAppFolder folder.
        /// </summary>
        [RepositoryFolder("e104cb91-fc1f-43a9-b07b-f4d65a9dd567")]
        public partial class EasternOnlineBankingDashboardAppFolder : RepoGenBaseFolder
        {
            SupportRepositoryFolders.DivTagRowFolder _divtagrow;
            RepoItemInfo _supportInfo;
            RepoItemInfo _ptagbusinessaccountinquiriesInfo;
            RepoItemInfo _atag18003338000Info;
            RepoItemInfo _monfriInfo;
            RepoItemInfo _spantag800am600pmInfo;
            RepoItemInfo _easternbanksautomatedaccountinformatInfo;
            RepoItemInfo _divtag1800eastern3278376Info;
            RepoItemInfo _contactusInfo;

            /// <summary>
            /// Creates a new EasternOnlineBankingDashboard  folder.
            /// </summary>
            public EasternOnlineBankingDashboardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EasternOnlineBankingDashboard", "/dom[@domain~'fnclmob.']", parentFolder, 30000, null, false, "e104cb91-fc1f-43a9-b07b-f4d65a9dd567", "")
            {
                _divtagrow = new SupportRepositoryFolders.DivTagRowFolder(this);
                _supportInfo = new RepoItemInfo(this, "Support", ".//a[#'Support']", 30000, null, "c52ece20-1fd3-4819-9437-e4ca0504c7ee");
                _ptagbusinessaccountinquiriesInfo = new RepoItemInfo(this, "PTagBusinessAccountInquiries", "body/div[2]/div/div/div/div[4]/p[@innertext~'^\\ Business\\ Account\\ Inquiri']", 30000, null, "9473865e-6890-4a17-a99a-64999725dbf2");
                _atag18003338000Info = new RepoItemInfo(this, "ATag18003338000", "body/div[2]/div/div/div/div[4]/a[@innertext='1-800-333-8000']", 30000, null, "41da32e5-4006-4aa1-87f0-d5a5992c24d1");
                _monfriInfo = new RepoItemInfo(this, "MonFri", "body/div[2]/div/div/div/div[5]/p[@innertext='Mon - Fri ']", 30000, null, "fd5851e8-68ce-45ba-b501-585de3b2bb4a");
                _spantag800am600pmInfo = new RepoItemInfo(this, "SpanTag800AM600PM", "body/div[2]/div/div/div/div[5]/p[@innertext='Mon - Fri ']/span[@innertext='8:00 AM - 6:00 PM']", 30000, null, "66240c36-c0ae-452c-8bb4-b39067cb1a8a");
                _easternbanksautomatedaccountinformatInfo = new RepoItemInfo(this, "EasternBanksAutomatedAccountInformat", "body/div[2]//div[@innertext~'^Eastern\\ Bank''s\\ automated\\ ']", 30000, null, "d54a9e07-9ef7-4414-9c60-33f6dde393e0");
                _divtag1800eastern3278376Info = new RepoItemInfo(this, "DivTag1800EASTERN3278376", "body/div[2]//div[@innertext~'^Eastern\\ Bank''s\\ automated\\ ']/div[@innertext~'^\\ \\ \\ 1-800-EASTERN\\ \\(327-837']", 30000, null, "a03f3af8-0956-4f72-a87b-b1c19d2d5fc2");
                _contactusInfo = new RepoItemInfo(this, "ContactUs", ".//body[#'outerTab']/form[@name='AuthenticationFG']//a[@innertext=' Contact Us  ']", 30000, null, "e5e76e3b-1163-4bc2-be6d-0b49cd1fd0af");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e104cb91-fc1f-43a9-b07b-f4d65a9dd567")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e104cb91-fc1f-43a9-b07b-f4d65a9dd567")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Support item.
            /// </summary>
            [RepositoryItem("c52ece20-1fd3-4819-9437-e4ca0504c7ee")]
            public virtual Ranorex.ATag Support
            {
                get
                {
                    return _supportInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Support item info.
            /// </summary>
            [RepositoryItemInfo("c52ece20-1fd3-4819-9437-e4ca0504c7ee")]
            public virtual RepoItemInfo SupportInfo
            {
                get
                {
                    return _supportInfo;
                }
            }

            /// <summary>
            /// The PTagBusinessAccountInquiries item.
            /// </summary>
            [RepositoryItem("9473865e-6890-4a17-a99a-64999725dbf2")]
            public virtual Ranorex.PTag PTagBusinessAccountInquiries
            {
                get
                {
                    return _ptagbusinessaccountinquiriesInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The PTagBusinessAccountInquiries item info.
            /// </summary>
            [RepositoryItemInfo("9473865e-6890-4a17-a99a-64999725dbf2")]
            public virtual RepoItemInfo PTagBusinessAccountInquiriesInfo
            {
                get
                {
                    return _ptagbusinessaccountinquiriesInfo;
                }
            }

            /// <summary>
            /// The ATag18003338000 item.
            /// </summary>
            [RepositoryItem("41da32e5-4006-4aa1-87f0-d5a5992c24d1")]
            public virtual Ranorex.ATag ATag18003338000
            {
                get
                {
                    return _atag18003338000Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATag18003338000 item info.
            /// </summary>
            [RepositoryItemInfo("41da32e5-4006-4aa1-87f0-d5a5992c24d1")]
            public virtual RepoItemInfo ATag18003338000Info
            {
                get
                {
                    return _atag18003338000Info;
                }
            }

            /// <summary>
            /// The MonFri item.
            /// </summary>
            [RepositoryItem("fd5851e8-68ce-45ba-b501-585de3b2bb4a")]
            public virtual Ranorex.PTag MonFri
            {
                get
                {
                    return _monfriInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The MonFri item info.
            /// </summary>
            [RepositoryItemInfo("fd5851e8-68ce-45ba-b501-585de3b2bb4a")]
            public virtual RepoItemInfo MonFriInfo
            {
                get
                {
                    return _monfriInfo;
                }
            }

            /// <summary>
            /// The SpanTag800AM600PM item.
            /// </summary>
            [RepositoryItem("66240c36-c0ae-452c-8bb4-b39067cb1a8a")]
            public virtual Ranorex.SpanTag SpanTag800AM600PM
            {
                get
                {
                    return _spantag800am600pmInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTag800AM600PM item info.
            /// </summary>
            [RepositoryItemInfo("66240c36-c0ae-452c-8bb4-b39067cb1a8a")]
            public virtual RepoItemInfo SpanTag800AM600PMInfo
            {
                get
                {
                    return _spantag800am600pmInfo;
                }
            }

            /// <summary>
            /// The EasternBanksAutomatedAccountInformat item.
            /// </summary>
            [RepositoryItem("d54a9e07-9ef7-4414-9c60-33f6dde393e0")]
            public virtual Ranorex.DivTag EasternBanksAutomatedAccountInformat
            {
                get
                {
                    return _easternbanksautomatedaccountinformatInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The EasternBanksAutomatedAccountInformat item info.
            /// </summary>
            [RepositoryItemInfo("d54a9e07-9ef7-4414-9c60-33f6dde393e0")]
            public virtual RepoItemInfo EasternBanksAutomatedAccountInformatInfo
            {
                get
                {
                    return _easternbanksautomatedaccountinformatInfo;
                }
            }

            /// <summary>
            /// The DivTag1800EASTERN3278376 item.
            /// </summary>
            [RepositoryItem("a03f3af8-0956-4f72-a87b-b1c19d2d5fc2")]
            public virtual Ranorex.DivTag DivTag1800EASTERN3278376
            {
                get
                {
                    return _divtag1800eastern3278376Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTag1800EASTERN3278376 item info.
            /// </summary>
            [RepositoryItemInfo("a03f3af8-0956-4f72-a87b-b1c19d2d5fc2")]
            public virtual RepoItemInfo DivTag1800EASTERN3278376Info
            {
                get
                {
                    return _divtag1800eastern3278376Info;
                }
            }

            /// <summary>
            /// The ContactUs item.
            /// </summary>
            [RepositoryItem("e5e76e3b-1163-4bc2-be6d-0b49cd1fd0af")]
            public virtual Ranorex.ATag ContactUs
            {
                get
                {
                    return _contactusInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ContactUs item info.
            /// </summary>
            [RepositoryItemInfo("e5e76e3b-1163-4bc2-be6d-0b49cd1fd0af")]
            public virtual RepoItemInfo ContactUsInfo
            {
                get
                {
                    return _contactusInfo;
                }
            }

            /// <summary>
            /// The DivTagRow folder.
            /// </summary>
            [RepositoryFolder("a1936efc-250f-438e-9f83-e3435b66961c")]
            public virtual SupportRepositoryFolders.DivTagRowFolder DivTagRow
            {
                get { return _divtagrow; }
            }
        }

        /// <summary>
        /// The DivTagRowFolder folder.
        /// </summary>
        [RepositoryFolder("a1936efc-250f-438e-9f83-e3435b66961c")]
        public partial class DivTagRowFolder : RepoGenBaseFolder
        {
            RepoItemInfo _callusInfo;
            RepoItemInfo _easternbanksautomatedaccountinformatInfo;
            RepoItemInfo _divtag1800eastern3278376Info;
            RepoItemInfo _httpsfnclmobqaeasternbankcom8543aInfo;
            RepoItemInfo _calluspanelInfo;
            RepoItemInfo _atag18004572043Info;
            RepoItemInfo _atag18882198359Info;
            RepoItemInfo _ptagbillpaymentsupportInfo;
            RepoItemInfo _ptagonlinebankingsupportInfo;

            /// <summary>
            /// Creates a new DivTagRow  folder.
            /// </summary>
            public DivTagRowFolder(RepoGenBaseFolder parentFolder) :
                    base("DivTagRow", ".//div[#'content']/div[2]/div[1]", parentFolder, 30000, null, false, "a1936efc-250f-438e-9f83-e3435b66961c", "")
            {
                _callusInfo = new RepoItemInfo(this, "CallUs", ".//div[@innertext='Call Us']", 30000, null, "b123acf4-5ceb-4597-a2bb-657eadf08d80");
                _easternbanksautomatedaccountinformatInfo = new RepoItemInfo(this, "EasternBanksAutomatedAccountInformat", ".//div[@innertext~'^Eastern\\ Bank''s\\ automated\\ ']", 30000, null, "bb04cd55-9696-4eea-aa3c-01399b8b207a");
                _divtag1800eastern3278376Info = new RepoItemInfo(this, "DivTag1800EASTERN3278376", ".//div[@innertext~'^Eastern\\ Bank''s\\ automated\\ ']/div[@innertext~'^\\ \\ \\ 1-800-EASTERN\\ \\(327-837']", 30000, null, "ff8fadca-ca3f-472f-bc61-80310cd321d2");
                _httpsfnclmobqaeasternbankcom8543aInfo = new RepoItemInfo(this, "HttpsFnclmobqaEasternbankCom8543A", ".//img[1]", 30000, null, "b89668ce-00e1-4b64-bf08-64357b636ed7");
                _calluspanelInfo = new RepoItemInfo(this, "CallUsPanel", "div/div/div/div", 30000, null, "11cc80a1-58ee-462f-a087-e18fb059e1e8");
                _atag18004572043Info = new RepoItemInfo(this, "ATag18004572043", "div/div/div/div/div[2]/a[@innertext='1-800-457-2043']", 30000, null, "2ed6303f-2e55-42ba-8db1-9c2e87631b39");
                _atag18882198359Info = new RepoItemInfo(this, "ATag18882198359", "div/div/div/div/div[2]/div/a[@innertext='1-888-219-8359']", 30000, null, "e21a8fc3-504a-4881-bc3a-49d041144255");
                _ptagbillpaymentsupportInfo = new RepoItemInfo(this, "PTagBillPaymentSupport", "div/div/div/div/div[2]/div/p[@innertext=' Bill Payment Support ']", 30000, null, "e6b84343-370b-4300-afe8-02d4bcdad340");
                _ptagonlinebankingsupportInfo = new RepoItemInfo(this, "PTagOnlineBankingSupport", "div/div/div/div/div[2]/p[@innertext=' Online Banking Support']", 30000, null, "3985ef85-9b7e-4ede-b57e-cd1d527078d8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a1936efc-250f-438e-9f83-e3435b66961c")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a1936efc-250f-438e-9f83-e3435b66961c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CallUs item.
            /// </summary>
            [RepositoryItem("b123acf4-5ceb-4597-a2bb-657eadf08d80")]
            public virtual Ranorex.DivTag CallUs
            {
                get
                {
                    return _callusInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CallUs item info.
            /// </summary>
            [RepositoryItemInfo("b123acf4-5ceb-4597-a2bb-657eadf08d80")]
            public virtual RepoItemInfo CallUsInfo
            {
                get
                {
                    return _callusInfo;
                }
            }

            /// <summary>
            /// The EasternBanksAutomatedAccountInformat item.
            /// </summary>
            [RepositoryItem("bb04cd55-9696-4eea-aa3c-01399b8b207a")]
            public virtual Ranorex.DivTag EasternBanksAutomatedAccountInformat
            {
                get
                {
                    return _easternbanksautomatedaccountinformatInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The EasternBanksAutomatedAccountInformat item info.
            /// </summary>
            [RepositoryItemInfo("bb04cd55-9696-4eea-aa3c-01399b8b207a")]
            public virtual RepoItemInfo EasternBanksAutomatedAccountInformatInfo
            {
                get
                {
                    return _easternbanksautomatedaccountinformatInfo;
                }
            }

            /// <summary>
            /// The DivTag1800EASTERN3278376 item.
            /// </summary>
            [RepositoryItem("ff8fadca-ca3f-472f-bc61-80310cd321d2")]
            public virtual Ranorex.DivTag DivTag1800EASTERN3278376
            {
                get
                {
                    return _divtag1800eastern3278376Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTag1800EASTERN3278376 item info.
            /// </summary>
            [RepositoryItemInfo("ff8fadca-ca3f-472f-bc61-80310cd321d2")]
            public virtual RepoItemInfo DivTag1800EASTERN3278376Info
            {
                get
                {
                    return _divtag1800eastern3278376Info;
                }
            }

            /// <summary>
            /// The HttpsFnclmobqaEasternbankCom8543A item.
            /// </summary>
            [RepositoryItem("b89668ce-00e1-4b64-bf08-64357b636ed7")]
            public virtual Ranorex.ImgTag HttpsFnclmobqaEasternbankCom8543A
            {
                get
                {
                    return _httpsfnclmobqaeasternbankcom8543aInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsFnclmobqaEasternbankCom8543A item info.
            /// </summary>
            [RepositoryItemInfo("b89668ce-00e1-4b64-bf08-64357b636ed7")]
            public virtual RepoItemInfo HttpsFnclmobqaEasternbankCom8543AInfo
            {
                get
                {
                    return _httpsfnclmobqaeasternbankcom8543aInfo;
                }
            }

            /// <summary>
            /// The CallUsPanel item.
            /// </summary>
            [RepositoryItem("11cc80a1-58ee-462f-a087-e18fb059e1e8")]
            public virtual Ranorex.DivTag CallUsPanel
            {
                get
                {
                    return _calluspanelInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CallUsPanel item info.
            /// </summary>
            [RepositoryItemInfo("11cc80a1-58ee-462f-a087-e18fb059e1e8")]
            public virtual RepoItemInfo CallUsPanelInfo
            {
                get
                {
                    return _calluspanelInfo;
                }
            }

            /// <summary>
            /// The ATag18004572043 item.
            /// </summary>
            [RepositoryItem("2ed6303f-2e55-42ba-8db1-9c2e87631b39")]
            public virtual Ranorex.ATag ATag18004572043
            {
                get
                {
                    return _atag18004572043Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATag18004572043 item info.
            /// </summary>
            [RepositoryItemInfo("2ed6303f-2e55-42ba-8db1-9c2e87631b39")]
            public virtual RepoItemInfo ATag18004572043Info
            {
                get
                {
                    return _atag18004572043Info;
                }
            }

            /// <summary>
            /// The ATag18882198359 item.
            /// </summary>
            [RepositoryItem("e21a8fc3-504a-4881-bc3a-49d041144255")]
            public virtual Ranorex.ATag ATag18882198359
            {
                get
                {
                    return _atag18882198359Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATag18882198359 item info.
            /// </summary>
            [RepositoryItemInfo("e21a8fc3-504a-4881-bc3a-49d041144255")]
            public virtual RepoItemInfo ATag18882198359Info
            {
                get
                {
                    return _atag18882198359Info;
                }
            }

            /// <summary>
            /// The PTagBillPaymentSupport item.
            /// </summary>
            [RepositoryItem("e6b84343-370b-4300-afe8-02d4bcdad340")]
            public virtual Ranorex.PTag PTagBillPaymentSupport
            {
                get
                {
                    return _ptagbillpaymentsupportInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The PTagBillPaymentSupport item info.
            /// </summary>
            [RepositoryItemInfo("e6b84343-370b-4300-afe8-02d4bcdad340")]
            public virtual RepoItemInfo PTagBillPaymentSupportInfo
            {
                get
                {
                    return _ptagbillpaymentsupportInfo;
                }
            }

            /// <summary>
            /// The PTagOnlineBankingSupport item.
            /// </summary>
            [RepositoryItem("3985ef85-9b7e-4ede-b57e-cd1d527078d8")]
            public virtual Ranorex.PTag PTagOnlineBankingSupport
            {
                get
                {
                    return _ptagonlinebankingsupportInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The PTagOnlineBankingSupport item info.
            /// </summary>
            [RepositoryItemInfo("3985ef85-9b7e-4ede-b57e-cd1d527078d8")]
            public virtual RepoItemInfo PTagOnlineBankingSupportInfo
            {
                get
                {
                    return _ptagonlinebankingsupportInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
