///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AccountsTestSuite.AlertsTab
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AlertsTabValidation recording.
    /// </summary>
    [TestModule("d77c509b-fb1f-40c9-9f5b-d326c9c5b275", ModuleType.Recording, 1)]
    public partial class AlertsTabValidation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AccountsTestSuite.AccountsTestSuiteRepository repository.
        /// </summary>
        public static global::AccountsTestSuite.AccountsTestSuiteRepository repo = global::AccountsTestSuite.AccountsTestSuiteRepository.Instance;

        static AlertsTabValidation instance = new AlertsTabValidation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AlertsTabValidation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AlertsTabValidation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbMode'", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbModeInfo, new RecordItemIndex(0));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbModeInfo.WaitForAttributeEqual(30000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingAuthenticationSc.AlertsTab.SendAlertsToHeader'", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.SendAlertsToHeaderInfo, new RecordItemIndex(1));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.SendAlertsToHeaderInfo.WaitForAttributeEqual(30000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.EditButton'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditButtonInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSwitch'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSwitchInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSwitchInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.BalanceIsBelowRow'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.BalanceIsBelowRowInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.BalanceIsBelowRowInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.BalanceIsAboveRow'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.BalanceIsAboveRowInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.BalanceIsAboveRowInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.WhenAnOverdraftOccursRow'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.WhenAnOverdraftOccursRowInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.WhenAnOverdraftOccursRowInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.WhenADepositIsMadeRow'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.WhenADepositIsMadeRowInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.WhenADepositIsMadeRowInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.WhenAnOnlineTransferIsSentRow'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.WhenAnOnlineTransferIsSentRowInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.WhenAnOnlineTransferIsSentRowInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.WhenACheckNumberClearsRow'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.WhenACheckNumberClearsRowInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.WhenACheckNumberClearsRowInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.ClearedCheckAmountAboveRow'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.ClearedCheckAmountAboveRowInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.ClearedCheckAmountAboveRowInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.MessageAndDataRatesInfo'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.MessageAndDataRatesInfoInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.MessageAndDataRatesInfoInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.MessageAndDataRatesInfo'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.MessageAndDataRatesInfoInfo, new RecordItemIndex(12));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.MessageAndDataRatesInfo.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'EasternOnlineBankingAuthenticationSc.AccountTabs.AlertsTab'.", repo.EasternOnlineBankingAuthenticationSc.AccountTabs.AlertsTabInfo, new RecordItemIndex(13));
            repo.EasternOnlineBankingAuthenticationSc.AccountTabs.AlertsTab.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.EditButton'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditButtonInfo, new RecordItemIndex(14));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditButton.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal'", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.SelfInfo, new RecordItemIndex(15));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.SelfInfo.WaitForAttributeEqual(5000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.EditContactInformationHeader'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.EditContactInformationHeaderInfo, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.EditContactInformationHeaderInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.EmailInputBox'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.EmailInputBoxInfo, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.EmailInputBoxInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.MobileNumberInputBox'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.MobileNumberInputBoxInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.MobileNumberInputBoxInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.CancelButton'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.CancelButtonInfo, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.CancelButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.SaveButton'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.SaveButtonInfo, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.SaveButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '' on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.EmailInputBox'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.EmailInputBoxInfo, new RecordItemIndex(21));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.EmailInputBox.Element.SetAttributeValue("TagValue", "");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '' on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.MobileNumberInputBox'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.MobileNumberInputBoxInfo, new RecordItemIndex(22));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.MobileNumberInputBox.Element.SetAttributeValue("TagValue", "");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.SaveButton'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.SaveButtonInfo, new RecordItemIndex(23));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.SaveButton.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.Errors.PleaseCorrectTheFollowingFieldsError'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.Errors.PleaseCorrectTheFollowingFieldsErrorInfo, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.Errors.PleaseCorrectTheFollowingFieldsErrorInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.Errors.InvalidEmailAddressError'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.Errors.InvalidEmailAddressErrorInfo, new RecordItemIndex(25));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.Errors.InvalidEmailAddressErrorInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.CancelButton'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.CancelButtonInfo, new RecordItemIndex(26));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.EditContactInformationModal.CancelButton.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbToggle'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbToggleInfo, new RecordItemIndex(27));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbToggle.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 20s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbTime'", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbTimeInfo, new RecordItemIndex(28));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbTimeInfo.WaitForAttributeEqual(20000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbTime'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbTimeInfo, new RecordItemIndex(29));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbTime.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal'", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.SelfInfo, new RecordItemIndex(30));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.SelfInfo.WaitForAttributeEqual(15000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.IDoNotWantToReceiveAlertsBetween'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.IDoNotWantToReceiveAlertsBetweenInfo, new RecordItemIndex(31));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.IDoNotWantToReceiveAlertsBetweenInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.StartTimeHour'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.StartTimeHourInfo, new RecordItemIndex(32));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.StartTimeHourInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.StartTimeMinute'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.StartTimeMinuteInfo, new RecordItemIndex(33));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.StartTimeMinuteInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.StartTimeAMPM'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.StartTimeAMPMInfo, new RecordItemIndex(34));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.StartTimeAMPMInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.EndTime'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.EndTimeInfo, new RecordItemIndex(35));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.EndTimeInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.EndTimeHour'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.EndTimeHourInfo, new RecordItemIndex(36));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.EndTimeHourInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.EndTimeMinute'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.EndTimeMinuteInfo, new RecordItemIndex(37));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.EndTimeMinuteInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.EndTimeAMPM'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.EndTimeAMPMInfo, new RecordItemIndex(38));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.EndTimeAMPMInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneDropdown'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneDropdownInfo, new RecordItemIndex(39));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneDropdownInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneDropdown'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneDropdownInfo, new RecordItemIndex(40));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneDropdown.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneList.PacificTime'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneList.PacificTimeInfo, new RecordItemIndex(41));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneList.PacificTimeInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneList.MountainTime'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneList.MountainTimeInfo, new RecordItemIndex(42));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneList.MountainTimeInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneList.CentralTime'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneList.CentralTimeInfo, new RecordItemIndex(43));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneList.CentralTimeInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneList.EasternTime'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneList.EasternTimeInfo, new RecordItemIndex(44));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneList.EasternTimeInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneDropdown'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneDropdownInfo, new RecordItemIndex(45));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.TimeZoneDropdown.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.CancelButton'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.CancelButtonInfo, new RecordItemIndex(46));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.CancelButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.SaveButton'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.SaveButtonInfo, new RecordItemIndex(47));
            Validate.AttributeEqual(repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.SaveButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.CancelButton'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.CancelButtonInfo, new RecordItemIndex(48));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbSettingsModal.CancelButton.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(49));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbToggle'.", repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbToggleInfo, new RecordItemIndex(50));
            repo.EasternOnlineBankingAuthenticationSc.AlertsTab.DoNotDisturbToggle.PerformClick();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
