///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EasternBankRegression.Module_Recordings.MajorModules.BillPayTab
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddCompanyPayee recording.
    /// </summary>
    [TestModule("45105bc6-6782-434b-8d87-6095a96a5d4f", ModuleType.Recording, 1)]
    public partial class AddCompanyPayee : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EasternBankRegression.EasternBankRegressionRepository repository.
        /// </summary>
        public static global::EasternBankRegression.EasternBankRegressionRepository repo = global::EasternBankRegression.EasternBankRegressionRepository.Instance;

        static AddCompanyPayee instance = new AddCompanyPayee();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddCompanyPayee()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddCompanyPayee Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.BillPay'.", repo.EasternOnlineBankingDashboard.BillPayInfo, new RecordItemIndex(0));
            repo.EasternOnlineBankingDashboard.BillPay.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'EasternOnlineBankingDashboard.BillPayTabLoadingModal'.", repo.EasternOnlineBankingDashboard.BillPayTabLoadingModalInfo, new RecordItemIndex(1));
            repo.EasternOnlineBankingDashboard.BillPayTabLoadingModal.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'Visible' to equal the specified value 'False'. Associated repository item: 'EasternOnlineBankingDashboard.BillPayTabLoadingModal'", repo.EasternOnlineBankingDashboard.BillPayTabLoadingModalInfo, new RecordItemIndex(2));
            repo.EasternOnlineBankingDashboard.BillPayTabLoadingModalInfo.WaitForAttributeEqual(30000, "Visible", "False");
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.AddPayeeButton'.", repo.EasternOnlineBankingDashboard.AddPayeeButtonInfo, new RecordItemIndex(3));
            repo.EasternOnlineBankingDashboard.AddPayeeButton.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.AddPayeeModal'", repo.EasternOnlineBankingDashboard.AddPayeeModal.SelfInfo, new RecordItemIndex(4));
            repo.EasternOnlineBankingDashboard.AddPayeeModal.SelfInfo.WaitForAttributeEqual(30000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.AddPayeeModal.AddACompanyButton'.", repo.EasternOnlineBankingDashboard.AddPayeeModal.AddACompanyButtonInfo, new RecordItemIndex(5));
            repo.EasternOnlineBankingDashboard.AddPayeeModal.AddACompanyButton.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.SearchCompanyModal'", repo.EasternOnlineBankingDashboard.SearchCompanyModal.SelfInfo, new RecordItemIndex(6));
            repo.EasternOnlineBankingDashboard.SearchCompanyModal.SelfInfo.WaitForAttributeEqual(10000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.SearchCompanyModal.SearchCompanyHeader'.", repo.EasternOnlineBankingDashboard.SearchCompanyModal.SearchCompanyHeaderInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.SearchCompanyModal.SearchCompanyHeaderInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.SearchCompanyModal.SearchCompanyInputBox'.", repo.EasternOnlineBankingDashboard.SearchCompanyModal.SearchCompanyInputBoxInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.SearchCompanyModal.SearchCompanyInputBoxInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.SearchCompanyModal.BackButton'.", repo.EasternOnlineBankingDashboard.SearchCompanyModal.BackButtonInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.SearchCompanyModal.BackButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.SearchCompanyModal.AddPayeeButton'.", repo.EasternOnlineBankingDashboard.SearchCompanyModal.AddPayeeButtonInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.SearchCompanyModal.AddPayeeButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.SearchCompanyModal.SearchCompanyInputBox'.", repo.EasternOnlineBankingDashboard.SearchCompanyModal.SearchCompanyInputBoxInfo, new RecordItemIndex(11));
            repo.EasternOnlineBankingDashboard.SearchCompanyModal.SearchCompanyInputBox.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Discover' with focus on 'EasternOnlineBankingDashboard.SearchCompanyModal.SearchCompanyInputBox'.", repo.EasternOnlineBankingDashboard.SearchCompanyModal.SearchCompanyInputBoxInfo, new RecordItemIndex(12));
            repo.EasternOnlineBankingDashboard.SearchCompanyModal.SearchCompanyInputBox.PressKeys("Discover");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.SearchCompanyModal.DiscoverCreditCards'", repo.EasternOnlineBankingDashboard.SearchCompanyModal.DiscoverCreditCardsInfo, new RecordItemIndex(13));
            repo.EasternOnlineBankingDashboard.SearchCompanyModal.DiscoverCreditCardsInfo.WaitForAttributeEqual(5000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.SearchCompanyModal.DiscoverCreditCards'.", repo.EasternOnlineBankingDashboard.SearchCompanyModal.DiscoverCreditCardsInfo, new RecordItemIndex(14));
            repo.EasternOnlineBankingDashboard.SearchCompanyModal.DiscoverCreditCards.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.SearchCompanyModal.DiscoverSelected'", repo.EasternOnlineBankingDashboard.SearchCompanyModal.DiscoverSelectedInfo, new RecordItemIndex(15));
            repo.EasternOnlineBankingDashboard.SearchCompanyModal.DiscoverSelectedInfo.WaitForAttributeEqual(5000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.SearchCompanyModal.AddPayeeButton'.", repo.EasternOnlineBankingDashboard.SearchCompanyModal.AddPayeeButtonInfo, new RecordItemIndex(16));
            repo.EasternOnlineBankingDashboard.SearchCompanyModal.AddPayeeButton.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.EnterPayeeInformationModal'", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.SelfInfo, new RecordItemIndex(17));
            repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.SelfInfo.WaitForAttributeEqual(5000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.AccountNumberInputBox1'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AccountNumberInputBox1Info, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AccountNumberInputBox1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.AccountNumberInputBox1'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AccountNumberInputBox1Info, new RecordItemIndex(19));
            repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AccountNumberInputBox1.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '6011208954052457' with focus on 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.AccountNumberInputBox1'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AccountNumberInputBox1Info, new RecordItemIndex(20));
            repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AccountNumberInputBox1.PressKeys("6011208954052457");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.PayeeNicknameInputBox1'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.PayeeNicknameInputBox1Info, new RecordItemIndex(21));
            repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.PayeeNicknameInputBox1.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Aaa Discover Credit Card 123' with focus on 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.PayeeNicknameInputBox1'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.PayeeNicknameInputBox1Info, new RecordItemIndex(22));
            repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.PayeeNicknameInputBox1.PressKeys("Aaa Discover Credit Card 123");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddPayeeButton1'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddPayeeButton1Info, new RecordItemIndex(23));
            //repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddPayeeButton1.PerformClick();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(24));
            //Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddPayeeButton1'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddPayeeButton1Info, new RecordItemIndex(25));
            repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddPayeeButton1.PerformClick();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.EnterPayeeInformationModal'", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.SelfInfo, new RecordItemIndex(26));
            //repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.SelfInfo.WaitForAttributeEqual(10000, "Visible", "True");
            
            //Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddressLine1InputBox'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddressLine1InputBoxInfo, new RecordItemIndex(27));
            //repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddressLine1InputBox.PerformClick();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '195 Market St' with focus on 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddressLine1InputBox'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddressLine1InputBoxInfo, new RecordItemIndex(28));
            //repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddressLine1InputBox.PressKeys("195 Market St");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.CityInputBox'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.CityInputBoxInfo, new RecordItemIndex(29));
            //repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.CityInputBox.PerformClick();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Lynn' with focus on 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.CityInputBox'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.CityInputBoxInfo, new RecordItemIndex(30));
            //repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.CityInputBox.PressKeys("Lynn");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.StateDropdown'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.StateDropdownInfo, new RecordItemIndex(31));
            //repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.StateDropdown.PerformClick();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'MA' with focus on 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.StateDropdown'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.StateDropdownInfo, new RecordItemIndex(32));
            //repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.StateDropdown.PressKeys("MA");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.ZipCodeInputBox'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.ZipCodeInputBoxInfo, new RecordItemIndex(33));
            //repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.ZipCodeInputBox.PerformClick();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '01901' with focus on 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.ZipCodeInputBox'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.ZipCodeInputBoxInfo, new RecordItemIndex(34));
            //repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.ZipCodeInputBox.PressKeys("01901");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddPayeeButton'.", repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddPayeeButtonInfo, new RecordItemIndex(35));
            //repo.EasternOnlineBankingDashboard.EnterPayeeInformationModal.AddPayeeButton.PerformClick();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.SuccessAddPayeeModal'", repo.EasternOnlineBankingDashboard.SuccessAddPayeeModal.SelfInfo, new RecordItemIndex(36));
            repo.EasternOnlineBankingDashboard.SuccessAddPayeeModal.SelfInfo.WaitForAttributeEqual(60000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.SuccessAddPayeeModal.YouHaveAddedThisPayee'.", repo.EasternOnlineBankingDashboard.SuccessAddPayeeModal.YouHaveAddedThisPayeeInfo, new RecordItemIndex(37));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.SuccessAddPayeeModal.YouHaveAddedThisPayeeInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.SuccessAddPayeeModal.DoneButton'.", repo.EasternOnlineBankingDashboard.SuccessAddPayeeModal.DoneButtonInfo, new RecordItemIndex(38));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.SuccessAddPayeeModal.DoneButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'Visible' to equal the specified value 'False'. Associated repository item: 'EasternOnlineBankingDashboard.BillPayTabLoadingModal'", repo.EasternOnlineBankingDashboard.BillPayTabLoadingModalInfo, new RecordItemIndex(39));
            repo.EasternOnlineBankingDashboard.BillPayTabLoadingModalInfo.WaitForAttributeEqual(30000, "Visible", "False");
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.SuccessAddPayeeModal.DoneButton'.", repo.EasternOnlineBankingDashboard.SuccessAddPayeeModal.DoneButtonInfo, new RecordItemIndex(40));
            repo.EasternOnlineBankingDashboard.SuccessAddPayeeModal.DoneButton.PerformClick();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
