///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace FirstTimeEnrollment
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CertificateOfDepositValidation recording.
    /// </summary>
    [TestModule("75e2dee9-218f-41cb-873a-d68c0aec83b1", ModuleType.Recording, 1)]
    public partial class CertificateOfDepositValidation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the FirstTimeEnrollmentRepository repository.
        /// </summary>
        public static FirstTimeEnrollmentRepository repo = FirstTimeEnrollmentRepository.Instance;

        static CertificateOfDepositValidation instance = new CertificateOfDepositValidation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CertificateOfDepositValidation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CertificateOfDepositValidation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.PleasevalidateyourCertificateofDepositAccountHeader'.", repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.PleasevalidateyourCertificateofDepositAccountHeaderInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.PleasevalidateyourCertificateofDepositAccountHeaderInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.AccountNumberInputBox'.", repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.AccountNumberInputBoxInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.AccountNumberInputBoxInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.OriginalDepositAmountInputBox'.", repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.OriginalDepositAmountInputBoxInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.OriginalDepositAmountInputBoxInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.CaptchaImage'.", repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.CaptchaImageInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.CaptchaImageInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.RefreshIcon'.", repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.RefreshIconInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.RefreshIconInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.VerificationCodeInputBox'.", repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.VerificationCodeInputBoxInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.VerificationCodeInputBoxInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingOnlineBankingE.FooterButtons.BackButton'.", repo.EasternOnlineBankingOnlineBankingE.FooterButtons.BackButtonInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.EasternOnlineBankingOnlineBankingE.FooterButtons.BackButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingOnlineBankingE.FooterButtons.NextButton'.", repo.EasternOnlineBankingOnlineBankingE.FooterButtons.NextButtonInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.EasternOnlineBankingOnlineBankingE.FooterButtons.NextButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingOnlineBankingE.FooterButtons.NextButton'.", repo.EasternOnlineBankingOnlineBankingE.FooterButtons.NextButtonInfo, new RecordItemIndex(8));
            repo.EasternOnlineBankingOnlineBankingE.FooterButtons.NextButton.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.Errors.PleaseCorrectTheFollowingFieldsError'.", repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.Errors.PleaseCorrectTheFollowingFieldsErrorInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.Errors.PleaseCorrectTheFollowingFieldsErrorInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.Errors.InvalidAccountNumberError'.", repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.Errors.InvalidAccountNumberErrorInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.Errors.InvalidAccountNumberErrorInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.Errors.InvalidOriginalDepositError'.", repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.Errors.InvalidOriginalDepositErrorInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.Errors.InvalidOriginalDepositErrorInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.Errors.InvalidCaptchaError'.", repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.Errors.InvalidCaptchaErrorInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.EasternOnlineBankingOnlineBankingE.CertificateOfDepositPage.Errors.InvalidCaptchaErrorInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
