///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BillPayTestSuite.BillPayTab
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ShowInactivePayees recording.
    /// </summary>
    [TestModule("e3c84a17-47e6-4a3b-9ecd-dd7fc68401b5", ModuleType.Recording, 1)]
    public partial class ShowInactivePayees : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::BillPayTestSuite.BillPayTestSuiteRepository repository.
        /// </summary>
        public static global::BillPayTestSuite.BillPayTestSuiteRepository repo = global::BillPayTestSuite.BillPayTestSuiteRepository.Instance;

        static ShowInactivePayees instance = new ShowInactivePayees();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ShowInactivePayees()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ShowInactivePayees Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.BillPayTab.ShowSortDropdown1'.", repo.EasternOnlineBankingDashboard.BillPayTab.ShowSortDropdown1Info, new RecordItemIndex(0));
            repo.EasternOnlineBankingDashboard.BillPayTab.ShowSortDropdown1.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.BillPayTab.ShowSortDropdown.ActivePayeesOnly'.", repo.EasternOnlineBankingDashboard.BillPayTab.ShowSortDropdown.ActivePayeesOnlyInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.BillPayTab.ShowSortDropdown.ActivePayeesOnlyInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.BillPayTab.ShowSortDropdown.InactivePayeesOnly'.", repo.EasternOnlineBankingDashboard.BillPayTab.ShowSortDropdown.InactivePayeesOnlyInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.BillPayTab.ShowSortDropdown.InactivePayeesOnlyInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.BillPayTab.ShowSortDropdown.InactivePayeesOnly'.", repo.EasternOnlineBankingDashboard.BillPayTab.ShowSortDropdown.InactivePayeesOnlyInfo, new RecordItemIndex(3));
            repo.EasternOnlineBankingDashboard.BillPayTab.ShowSortDropdown.InactivePayeesOnly.PerformClick();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
