///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CRIF
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The HowMuchWouldYouLikeToBorrowPageValidation recording.
    /// </summary>
    [TestModule("d8c36483-54c4-474f-b874-0756eb2ac129", ModuleType.Recording, 1)]
    public partial class HowMuchWouldYouLikeToBorrowPageValidation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CRIFRepository repository.
        /// </summary>
        public static CRIFRepository repo = CRIFRepository.Instance;

        static HowMuchWouldYouLikeToBorrowPageValidation instance = new HowMuchWouldYouLikeToBorrowPageValidation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public HowMuchWouldYouLikeToBorrowPageValidation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static HowMuchWouldYouLikeToBorrowPageValidation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage'", repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.SelfInfo, new RecordItemIndex(0));
            repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.SelfInfo.WaitForAttributeEqual(5000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.LoanAmountInputBox'.", repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.LoanAmountInputBoxInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.LoanAmountInputBoxInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.Progressbar'.", repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.ProgressbarInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.ProgressbarInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.DollarAmount2000'.", repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.DollarAmount2000Info, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.DollarAmount2000Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.DollarAmount25000'.", repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.DollarAmount25000Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.DollarAmount25000Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.WhenWouldYouLikeToPayOffThisLoan'.", repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.WhenWouldYouLikeToPayOffThisLoanInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.WhenWouldYouLikeToPayOffThisLoanInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.OneYearButton'.", repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.OneYearButtonInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.OneYearButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.TwoYearsButton'.", repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.TwoYearsButtonInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.TwoYearsButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.ThreeYearsButton'.", repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.ThreeYearsButtonInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.ThreeYearsButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.FourYearsButton'.", repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.FourYearsButtonInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.FourYearsButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.FiveYearsButton'.", repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.FiveYearsButtonInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.FiveYearsButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.BackButton'.", repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.BackButtonInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.BackButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.ContinueButton'", repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.ContinueButtonInfo, new RecordItemIndex(12));
            repo.EasternOnlineBankingDashboard.HowMuchWouldYouLikeToBorrowPage.ContinueButtonInfo.WaitForAttributeEqual(10000, "Visible", "True");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
