///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EasternBankRegression.Module_Recordings.MajorModules.SettingsTab
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The editsave recording.
    /// </summary>
    [TestModule("c3802664-7873-4ce6-9d2c-22864f78fa6d", ModuleType.Recording, 1)]
    public partial class editsave : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EasternBankRegression.EasternBankRegressionRepository repository.
        /// </summary>
        public static global::EasternBankRegression.EasternBankRegressionRepository repo = global::EasternBankRegression.EasternBankRegressionRepository.Instance;

        static editsave instance = new editsave();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public editsave()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static editsave Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MajorModules.Settings_Sub.ProfileSub.EditusernameSave' at Center.", repo.ApplicationUnderTest.MajorModules.Settings_Sub.ProfileSub.EditusernameSaveInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.MajorModules.Settings_Sub.ProfileSub.EditusernameSave.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'ApplicationUnderTest.MajorModules.Settings_Sub.ProfileSub.DoneForNewUserName'.", repo.ApplicationUnderTest.MajorModules.Settings_Sub.ProfileSub.DoneForNewUserNameInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.MajorModules.Settings_Sub.ProfileSub.DoneForNewUserName.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MajorModules.Settings_Sub.ProfileSub.DoneForNewUserName' at Center.", repo.ApplicationUnderTest.MajorModules.Settings_Sub.ProfileSub.DoneForNewUserNameInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.MajorModules.Settings_Sub.ProfileSub.DoneForNewUserName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.MajorModules.Settings_Sub.ProfileSub.QAtAton1Validate'.", repo.ApplicationUnderTest.MajorModules.Settings_Sub.ProfileSub.QAtAton1ValidateInfo, new RecordItemIndex(4));
            Validate.Exists(repo.ApplicationUnderTest.MajorModules.Settings_Sub.ProfileSub.QAtAton1ValidateInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
