///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EasternBankRegression.Module_Recordings.MajorModules.TransfersTab
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Regularloanpaymentonetimescheduled recording.
    /// </summary>
    [TestModule("87cfe7bf-4e35-4023-b8cb-9a598c4932fb", ModuleType.Recording, 1)]
    public partial class Regularloanpaymentonetimescheduled : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EasternBankRegression.EasternBankRegressionRepository repository.
        /// </summary>
        public static global::EasternBankRegression.EasternBankRegressionRepository repo = global::EasternBankRegression.EasternBankRegressionRepository.Instance;

        static Regularloanpaymentonetimescheduled instance = new Regularloanpaymentonetimescheduled();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Regularloanpaymentonetimescheduled()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Regularloanpaymentonetimescheduled Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.Transfers'.", repo.EasternOnlineBankingDashboard.TransfersInfo, new RecordItemIndex(0));
            repo.EasternOnlineBankingDashboard.Transfers.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.InternalTransfersCard'", repo.EasternOnlineBankingDashboard.InternalTransfersCard.SelfInfo, new RecordItemIndex(2));
            repo.EasternOnlineBankingDashboard.InternalTransfersCard.SelfInfo.WaitForAttributeEqual(30000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(3));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'ApplicationUnderTest.MajorModules.Transfers_Sub.MakeTransferBWBankAcc'.", repo.ApplicationUnderTest.MajorModules.Transfers_Sub.MakeTransferBWBankAccInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.MajorModules.Transfers_Sub.MakeTransferBWBankAcc.Element.InvokeActionWithText("PerformClick");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.InternalTransferModal'", repo.EasternOnlineBankingDashboard.InternalTransferModal.SelfInfo, new RecordItemIndex(5));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.SelfInfo.WaitForAttributeEqual(60000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InternalTransferModal.TransferFromDropdown'.", repo.EasternOnlineBankingDashboard.InternalTransferModal.TransferFromDropdownInfo, new RecordItemIndex(6));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.TransferFromDropdown.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'ApplicationUnderTest.MajorModules.Transfers_Sub.TransferBetweenMyEAsternBankAccoutns.SelectChecking7927'.", repo.ApplicationUnderTest.MajorModules.Transfers_Sub.TransferBetweenMyEAsternBankAccoutns.SelectChecking7927Info, new RecordItemIndex(8));
            repo.ApplicationUnderTest.MajorModules.Transfers_Sub.TransferBetweenMyEAsternBankAccoutns.SelectChecking7927.Element.InvokeActionWithText("PerformClick");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InternalTransferModal.TransferToDropdown'.", repo.EasternOnlineBankingDashboard.InternalTransferModal.TransferToDropdownInfo, new RecordItemIndex(9));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.TransferToDropdown.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(10));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EasternOnlineBankingDashboard.InternalTransferModal.Search' at Center.", repo.EasternOnlineBankingDashboard.InternalTransferModal.SearchInfo, new RecordItemIndex(11));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.Search.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(12));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(13));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(14));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(15));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(16));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(17));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(18));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(19));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(20));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(21));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(22));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(23));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(24));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(25));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(26));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(27));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InternalTransferModal.varToLoanAccount'.", repo.EasternOnlineBankingDashboard.InternalTransferModal.varToLoanAccountInfo, new RecordItemIndex(28));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.varToLoanAccount.Element.InvokeActionWithText("PerformClick");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EasternOnlineBankingDashboard.InternalTransferModal.TransferAmountInputBox' at Center.", repo.EasternOnlineBankingDashboard.InternalTransferModal.TransferAmountInputBoxInfo, new RecordItemIndex(29));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.TransferAmountInputBox.Click(10);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '1' Press with focus on 'ApplicationUnderTest.MajorModules.Transfers_Sub.TransferBetweenMyEAsternBankAccoutns.AmountToTransferBetweenMyEasternBankAccounts'.", repo.ApplicationUnderTest.MajorModules.Transfers_Sub.TransferBetweenMyEAsternBankAccoutns.AmountToTransferBetweenMyEasternBankAccountsInfo, new RecordItemIndex(30));
            Keyboard.PrepareFocus(repo.ApplicationUnderTest.MajorModules.Transfers_Sub.TransferBetweenMyEAsternBankAccoutns.AmountToTransferBetweenMyEasternBankAccounts);
            Keyboard.Press(System.Windows.Forms.Keys.D1, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InternalTransferModal.FrequencyDropdown'.", repo.EasternOnlineBankingDashboard.InternalTransferModal.FrequencyDropdownInfo, new RecordItemIndex(31));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.FrequencyDropdown.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EasternOnlineBankingDashboard.InternalTransferModal.OneTimeScheduled' at Center.", repo.EasternOnlineBankingDashboard.InternalTransferModal.OneTimeScheduledInfo, new RecordItemIndex(32));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.OneTimeScheduled.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EasternOnlineBankingDashboard.InternalTransferModal.ClickDate' at Center.", repo.EasternOnlineBankingDashboard.InternalTransferModal.ClickDateInfo, new RecordItemIndex(33));
            repo.EasternOnlineBankingDashboard.InternalTransferModal.ClickDate.Click();
            Delay.Milliseconds(200);
            
            Module_Code.GeneralLibrary.Currentdate();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.ConfirmButton'.", repo.EasternOnlineBankingDashboard.ConfirmButtonInfo, new RecordItemIndex(35));
            repo.EasternOnlineBankingDashboard.ConfirmButton.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(36));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.TransferSuccessfulModal.From'.", repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.FromInfo, new RecordItemIndex(37));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.FromInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.TransferSuccessfulModal.To'.", repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.ToInfo, new RecordItemIndex(38));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.ToInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.TransferSuccessfulModal.LoanPaymentType'.", repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.LoanPaymentTypeInfo, new RecordItemIndex(39));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.LoanPaymentTypeInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.TransferSuccessfulModal.Frequency'.", repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.FrequencyInfo, new RecordItemIndex(40));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.FrequencyInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.TransferSuccessfulModal.TransferOn'.", repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.TransferOnInfo, new RecordItemIndex(41));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.TransferSuccessfulModal.TransferOnInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
