///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Settings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeleteTransactionCategory recording.
    /// </summary>
    [TestModule("0dec06b2-08c5-4e6f-9233-bfecdd887356", ModuleType.Recording, 1)]
    public partial class DeleteTransactionCategory : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SettingsRepository repository.
        /// </summary>
        public static SettingsRepository repo = SettingsRepository.Instance;

        static DeleteTransactionCategory instance = new DeleteTransactionCategory();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeleteTransactionCategory()
        {
            Category_Name = "Test Category 1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeleteTransactionCategory Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Category_Name.
        /// </summary>
        [TestVariable("fbc368bf-f5f9-4f87-952c-c92e47576af2")]
        public string Category_Name
        {
            get { return repo.Category_Name; }
            set { repo.Category_Name = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 10;
            Keyboard.DefaultKeyPressTime = 10;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.ManageCategoriesModal.CategoryNameVar'.", repo.EasternOnlineBankingDashboard.ManageCategoriesModal.CategoryNameVarInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.ManageCategoriesModal.CategoryNameVarInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.ManageCategoriesModal.Edit'.", repo.EasternOnlineBankingDashboard.ManageCategoriesModal.EditInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.ManageCategoriesModal.EditInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.ManageCategoriesModal.Delete'.", repo.EasternOnlineBankingDashboard.ManageCategoriesModal.DeleteInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.ManageCategoriesModal.DeleteInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.ManageCategoriesModal.Delete'.", repo.EasternOnlineBankingDashboard.ManageCategoriesModal.DeleteInfo, new RecordItemIndex(3));
            repo.EasternOnlineBankingDashboard.ManageCategoriesModal.Delete.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(4));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.ManageCategoriesModal.DoneButton'.", repo.EasternOnlineBankingDashboard.ManageCategoriesModal.DoneButtonInfo, new RecordItemIndex(5));
            repo.EasternOnlineBankingDashboard.ManageCategoriesModal.DoneButton.PerformClick();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
