///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EasternBankRegression.Module_Recordings.MajorModules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FirstTime recording.
    /// </summary>
    [TestModule("54a9ad0a-3c94-4b04-bc87-8515b57b2db6", ModuleType.Recording, 1)]
    public partial class FirstTime : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EasternBankRegression.EasternBankRegressionRepository repository.
        /// </summary>
        public static global::EasternBankRegression.EasternBankRegressionRepository repo = global::EasternBankRegression.EasternBankRegressionRepository.Instance;

        static FirstTime instance = new FirstTime();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FirstTime()
        {
            varBrowser = "";
            firstTimeEnrollmentUrl = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FirstTime Instance
        {
            get { return instance; }
        }

#region Variables

        string _varBrowser;

        /// <summary>
        /// Gets or sets the value of variable varBrowser.
        /// </summary>
        [TestVariable("7e885e20-6ecd-4779-99e0-51419e32ca4b")]
        public string varBrowser
        {
            get { return _varBrowser; }
            set { _varBrowser = value; }
        }

        string _firstTimeEnrollmentUrl;

        /// <summary>
        /// Gets or sets the value of variable firstTimeEnrollmentUrl.
        /// </summary>
        [TestVariable("a72d4d2b-1152-480c-8f7e-183a9241832a")]
        public string firstTimeEnrollmentUrl
        {
            get { return _firstTimeEnrollmentUrl; }
            set { _firstTimeEnrollmentUrl = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://fnclmobstg.easternbank.com/angular/AuthenticationController?FORMSGROUP_ID__=LoginAltFlowHomeFG&__START_TRAN_FLAG__=Y&FG_BUTTONS__=LOAD&ACTION.LOAD=Y&LoginAltFlowHomeFG.LOGIN_FLAG=6&LoginAltFlowHomeFG.VIEWID=1&BANK_ID=EBK\r\n' with browser specified by variable $varBrowser in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://fnclmobstg.easternbank.com/angular/AuthenticationController?FORMSGROUP_ID__=LoginAltFlowHomeFG&__START_TRAN_FLAG__=Y&FG_BUTTONS__=LOAD&ACTION.LOAD=Y&LoginAltFlowHomeFG.LOGIN_FLAG=6&LoginAltFlowHomeFG.VIEWID=1&BANK_ID=EBK\r\n", varBrowser, "", false, true, false, false, false, true);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.EasternBankJoinUsForGood'", repo.EasternOnlineBankingDashboard.EasternBankJoinUsForGoodInfo, new RecordItemIndex(1));
            repo.EasternOnlineBankingDashboard.EasternBankJoinUsForGoodInfo.WaitForAttributeEqual(15000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.SelectEnrollmentOptionMessage'.", repo.EasternOnlineBankingDashboard.SelectEnrollmentOptionMessageInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.SelectEnrollmentOptionMessageInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.EnrollMyPersonalAccounts'.", repo.EasternOnlineBankingDashboard.EnrollMyPersonalAccountsInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.EnrollMyPersonalAccountsInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.IHaveASocialSecurityNumber'.", repo.EasternOnlineBankingDashboard.IHaveASocialSecurityNumberInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.IHaveASocialSecurityNumberInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.EnrollMyBusinessAccounts'.", repo.EasternOnlineBankingDashboard.EnrollMyBusinessAccountsInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.EnrollMyBusinessAccountsInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.IHaveATaxIdentificationNumber'.", repo.EasternOnlineBankingDashboard.IHaveATaxIdentificationNumberInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.IHaveATaxIdentificationNumberInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.CancelButton5'.", repo.EasternOnlineBankingDashboard.CancelButton5Info, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.CancelButton5Info, "Visible", "True");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
