///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EasternBankRegression.Module_Recordings.MajorModules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MessageViewValidation recording.
    /// </summary>
    [TestModule("be5edcf0-e277-4789-b0b7-16005a4aaae3", ModuleType.Recording, 1)]
    public partial class MessageViewValidation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EasternBankRegression.EasternBankRegressionRepository repository.
        /// </summary>
        public static global::EasternBankRegression.EasternBankRegressionRepository repo = global::EasternBankRegression.EasternBankRegressionRepository.Instance;

        static MessageViewValidation instance = new MessageViewValidation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MessageViewValidation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MessageViewValidation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.Messages2'.", repo.EasternOnlineBankingDashboard.Messages2Info, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.Messages2Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.Messages2'.", repo.EasternOnlineBankingDashboard.Messages2Info, new RecordItemIndex(1));
            repo.EasternOnlineBankingDashboard.Messages2.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'EasternOnlineBankingDashboard.InboxLoadingModal'.", repo.EasternOnlineBankingDashboard.InboxLoadingModalInfo, new RecordItemIndex(2));
            repo.EasternOnlineBankingDashboard.InboxLoadingModal.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m for the attribute 'Visible' to equal the specified value 'False'. Associated repository item: 'EasternOnlineBankingDashboard.InboxLoadingModal'", repo.EasternOnlineBankingDashboard.InboxLoadingModalInfo, new RecordItemIndex(3));
            repo.EasternOnlineBankingDashboard.InboxLoadingModalInfo.WaitForAttributeEqual(60000, "Visible", "False");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.MessagesHeader'", repo.EasternOnlineBankingDashboard.MessagesHeaderInfo, new RecordItemIndex(4));
            repo.EasternOnlineBankingDashboard.MessagesHeaderInfo.WaitForAttributeEqual(15000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.ComposeNewMessageButton'.", repo.EasternOnlineBankingDashboard.ComposeNewMessageButtonInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.ComposeNewMessageButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.InboxTab'.", repo.EasternOnlineBankingDashboard.InboxTabInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.InboxTabInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.SentTab'.", repo.EasternOnlineBankingDashboard.SentTabInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.SentTabInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.TrashTab'.", repo.EasternOnlineBankingDashboard.TrashTabInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.TrashTabInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.InboxTab1'.", repo.EasternOnlineBankingDashboard.InboxTab1.SelfInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.InboxTab1.SelfInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.InboxTab1.SearchInputBox'.", repo.EasternOnlineBankingDashboard.InboxTab1.SearchInputBoxInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.InboxTab1.SearchInputBoxInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.InboxTab1.FirstMessage'.", repo.EasternOnlineBankingDashboard.InboxTab1.FirstMessageInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.InboxTab1.FirstMessageInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InboxTab1.FirstMessage'.", repo.EasternOnlineBankingDashboard.InboxTab1.FirstMessageInfo, new RecordItemIndex(12));
            repo.EasternOnlineBankingDashboard.InboxTab1.FirstMessage.Element.InvokeActionWithText("PerformClick");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.InboxTab1.From'", repo.EasternOnlineBankingDashboard.InboxTab1.FromInfo, new RecordItemIndex(13));
            repo.EasternOnlineBankingDashboard.InboxTab1.FromInfo.WaitForAttributeEqual(30000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.InboxTab1.BackButton'", repo.EasternOnlineBankingDashboard.InboxTab1.BackButtonInfo, new RecordItemIndex(14));
            repo.EasternOnlineBankingDashboard.InboxTab1.BackButtonInfo.WaitForAttributeEqual(30000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.InboxTab1.ReplyButton'.", repo.EasternOnlineBankingDashboard.InboxTab1.ReplyButtonInfo, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.InboxTab1.ReplyButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.InboxTab1.MoveToTrashButton'.", repo.EasternOnlineBankingDashboard.InboxTab1.MoveToTrashButtonInfo, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.InboxTab1.MoveToTrashButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.InboxTab1.PrintButton'.", repo.EasternOnlineBankingDashboard.InboxTab1.PrintButtonInfo, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.InboxTab1.PrintButtonInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.InboxTab1.From'.", repo.EasternOnlineBankingDashboard.InboxTab1.FromInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.InboxTab1.FromInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.InboxTab1.Subject'.", repo.EasternOnlineBankingDashboard.InboxTab1.SubjectInfo, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.InboxTab1.SubjectInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.InboxTab1.Date'.", repo.EasternOnlineBankingDashboard.InboxTab1.DateInfo, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.InboxTab1.DateInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.InboxTab1.RepliedInfo'.", repo.EasternOnlineBankingDashboard.InboxTab1.RepliedInfoInfo, new RecordItemIndex(21));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.InboxTab1.RepliedInfoInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.InboxTab1.ShowReplyButton'.", repo.EasternOnlineBankingDashboard.InboxTab1.ShowReplyButtonInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.InboxTab1.ShowReplyButtonInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.InboxTab1.MessageBody'.", repo.EasternOnlineBankingDashboard.InboxTab1.MessageBodyInfo, new RecordItemIndex(23));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.InboxTab1.MessageBodyInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InboxTab1.BackButton'.", repo.EasternOnlineBankingDashboard.InboxTab1.BackButtonInfo, new RecordItemIndex(24));
            repo.EasternOnlineBankingDashboard.InboxTab1.BackButton.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InboxTab1.FirstMessage'.", repo.EasternOnlineBankingDashboard.InboxTab1.FirstMessageInfo, new RecordItemIndex(25));
            repo.EasternOnlineBankingDashboard.InboxTab1.FirstMessage.Element.InvokeActionWithText("PerformClick");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.InboxTab1.From'", repo.EasternOnlineBankingDashboard.InboxTab1.FromInfo, new RecordItemIndex(26));
            repo.EasternOnlineBankingDashboard.InboxTab1.FromInfo.WaitForAttributeEqual(30000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.InboxTab1.ReplyButton'.", repo.EasternOnlineBankingDashboard.InboxTab1.ReplyButtonInfo, new RecordItemIndex(27));
            repo.EasternOnlineBankingDashboard.InboxTab1.ReplyButton.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.ReplyNewMessageModal'", repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.SelfInfo, new RecordItemIndex(28));
            repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.SelfInfo.WaitForAttributeEqual(5000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.ReplyNewMessageModal.ReplyNewMessageHeader'.", repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.ReplyNewMessageHeaderInfo, new RecordItemIndex(29));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.ReplyNewMessageHeaderInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.ReplyNewMessageModal.RETest'.", repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.RETestInfo, new RecordItemIndex(30));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.RETestInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.ReplyNewMessageModal.ReplyMessageTextArea'.", repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.ReplyMessageTextAreaInfo, new RecordItemIndex(31));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.ReplyMessageTextAreaInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.ReplyNewMessageModal.FromEasternBank'.", repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.FromEasternBankInfo, new RecordItemIndex(32));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.FromEasternBankInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.ReplyNewMessageModal.Subject'.", repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.SubjectInfo, new RecordItemIndex(33));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.SubjectInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.ReplyNewMessageModal.Date'.", repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.DateInfo, new RecordItemIndex(34));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.DateInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.ReplyNewMessageModal.MessageDetails'.", repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.MessageDetailsInfo, new RecordItemIndex(35));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.MessageDetailsInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'EasternOnlineBankingDashboard.ReplyNewMessageModal.SendMessageButton'.", repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.SendMessageButtonInfo, new RecordItemIndex(36));
            repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.SendMessageButton.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.ReplyNewMessageModal.CancelButton'.", repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.CancelButtonInfo, new RecordItemIndex(37));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.CancelButtonInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.ReplyNewMessageModal.SendMessageButton'.", repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.SendMessageButtonInfo, new RecordItemIndex(38));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.SendMessageButtonInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.ReplyNewMessageModal.CancelButton'.", repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.CancelButtonInfo, new RecordItemIndex(39));
            repo.EasternOnlineBankingDashboard.ReplyNewMessageModal.CancelButton.PerformClick();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
