///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Login
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SetupAndTeardownRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("5bfca4d2-e75d-48d4-811e-7ec90b3e7c33")]
    public partial class SetupAndTeardownRepository : RepoGenBaseFolder
    {
        static SetupAndTeardownRepository instance = new SetupAndTeardownRepository();
        SetupAndTeardownRepositoryFolders.FinacleAppFolder _finacle;
        SetupAndTeardownRepositoryFolders.HomepageEasternBankAppFolder _homepageeasternbank;
        SetupAndTeardownRepositoryFolders.EasternOnlineBankingForgotUserNameAppFolder _easternonlinebankingforgotusername;
        SetupAndTeardownRepositoryFolders.FirefoxAppFolder _firefox;
        SetupAndTeardownRepositoryFolders.ChromeAppFolder _chrome;
        SetupAndTeardownRepositoryFolders.IEAppFolder _ie;

        /// <summary>
        /// Gets the singleton class instance representing the SetupAndTeardownRepository element repository.
        /// </summary>
        [RepositoryFolder("5bfca4d2-e75d-48d4-811e-7ec90b3e7c33")]
        public static SetupAndTeardownRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SetupAndTeardownRepository() 
            : base("SetupAndTeardownRepository", "/", null, 0, false, "5bfca4d2-e75d-48d4-811e-7ec90b3e7c33", ".\\RepositoryImages\\SetupAndTeardownRepository5bfca4d2.rximgres")
        {
            _finacle = new SetupAndTeardownRepositoryFolders.FinacleAppFolder(this);
            _homepageeasternbank = new SetupAndTeardownRepositoryFolders.HomepageEasternBankAppFolder(this);
            _easternonlinebankingforgotusername = new SetupAndTeardownRepositoryFolders.EasternOnlineBankingForgotUserNameAppFolder(this);
            _firefox = new SetupAndTeardownRepositoryFolders.FirefoxAppFolder(this);
            _chrome = new SetupAndTeardownRepositoryFolders.ChromeAppFolder(this);
            _ie = new SetupAndTeardownRepositoryFolders.IEAppFolder(this);
        }

#region Variables

        string _Title = "";

        /// <summary>
        /// Gets or sets the value of variable Title.
        /// </summary>
        [TestVariable("f5f0bd62-b91a-4f91-ad4c-7ca1a739eb88")]
        public string Title
        {
            get { return _Title; }
            set { _Title = value; }
        }

        string _CheckingAccountType = "Premier Checking";

        /// <summary>
        /// Gets or sets the value of variable CheckingAccountType.
        /// </summary>
        [TestVariable("5e718e21-dabe-4c31-90f4-9c409a87ec39")]
        public string CheckingAccountType
        {
            get { return _CheckingAccountType; }
            set { _CheckingAccountType = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5bfca4d2-e75d-48d4-811e-7ec90b3e7c33")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Finacle folder.
        /// </summary>
        [RepositoryFolder("53dac7b1-0df7-4c8a-bc5b-6e2657c82d8b")]
        public virtual SetupAndTeardownRepositoryFolders.FinacleAppFolder Finacle
        {
            get { return _finacle; }
        }

        /// <summary>
        /// The HomepageEasternBank folder.
        /// </summary>
        [RepositoryFolder("7f5a8a12-532e-484a-b43d-f70638e0f8c8")]
        public virtual SetupAndTeardownRepositoryFolders.HomepageEasternBankAppFolder HomepageEasternBank
        {
            get { return _homepageeasternbank; }
        }

        /// <summary>
        /// The EasternOnlineBankingForgotUserName folder.
        /// </summary>
        [RepositoryFolder("dd7b5f94-36b4-488e-b4d9-c58143ce7b11")]
        public virtual SetupAndTeardownRepositoryFolders.EasternOnlineBankingForgotUserNameAppFolder EasternOnlineBankingForgotUserName
        {
            get { return _easternonlinebankingforgotusername; }
        }

        /// <summary>
        /// The Firefox folder.
        /// </summary>
        [RepositoryFolder("f42310c0-0ad1-4206-8690-ec2dc5b493da")]
        public virtual SetupAndTeardownRepositoryFolders.FirefoxAppFolder Firefox
        {
            get { return _firefox; }
        }

        /// <summary>
        /// The Chrome folder.
        /// </summary>
        [RepositoryFolder("825e415e-ae25-4ba0-8cca-5568664c8bd5")]
        public virtual SetupAndTeardownRepositoryFolders.ChromeAppFolder Chrome
        {
            get { return _chrome; }
        }

        /// <summary>
        /// The IE folder.
        /// </summary>
        [RepositoryFolder("fe6f8fa0-931f-4592-97b9-91536e9916a7")]
        public virtual SetupAndTeardownRepositoryFolders.IEAppFolder IE
        {
            get { return _ie; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SetupAndTeardownRepositoryFolders
    {
        /// <summary>
        /// The FinacleAppFolder folder.
        /// </summary>
        [RepositoryFolder("53dac7b1-0df7-4c8a-bc5b-6e2657c82d8b")]
        public partial class FinacleAppFolder : RepoGenBaseFolder
        {
            SetupAndTeardownRepositoryFolders.SupportPageColMd24Folder _supportpagecolmd24;
            SetupAndTeardownRepositoryFolders.LoginModalFolder _loginmodal;
            SetupAndTeardownRepositoryFolders.FooterFolder _footer;
            SetupAndTeardownRepositoryFolders.WelcomeAreaFolder _welcomearea;
            SetupAndTeardownRepositoryFolders.AccountsDashboardFolder _accountsdashboard;
            RepoItemInfo _invalidunorpwerrorInfo;
            RepoItemInfo _dropdownmenuInfo;
            RepoItemInfo _signoutInfo;
            RepoItemInfo _locnInfo;
            RepoItemInfo _checkingaccountvariableInfo;
            RepoItemInfo _openaccountheadervariableInfo;

            /// <summary>
            /// Creates a new Finacle  folder.
            /// </summary>
            public FinacleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Finacle", "/dom[@domain~'fnclmob.']", parentFolder, 30000, null, false, "53dac7b1-0df7-4c8a-bc5b-6e2657c82d8b", "")
            {
                _supportpagecolmd24 = new SetupAndTeardownRepositoryFolders.SupportPageColMd24Folder(this);
                _loginmodal = new SetupAndTeardownRepositoryFolders.LoginModalFolder(this);
                _footer = new SetupAndTeardownRepositoryFolders.FooterFolder(this);
                _welcomearea = new SetupAndTeardownRepositoryFolders.WelcomeAreaFolder(this);
                _accountsdashboard = new SetupAndTeardownRepositoryFolders.AccountsDashboardFolder(this);
                _invalidunorpwerrorInfo = new RepoItemInfo(this, "InvalidUNorPWError", ".//div[#'MessageDisplay_TABLE']/div[@innertext='You have entered an invalid username or password. Please try again or call us at 1-800-457-2043 if you need assistance.']", 30000, null, "6321f47b-c2d4-43fb-88db-ed6d535b17c2");
                _dropdownmenuInfo = new RepoItemInfo(this, "DropdownMenu", ".//img[@id='eyeDark']", 30000, null, "dfbdcf83-1e6d-4071-b4a5-fea766c3a670");
                _signoutInfo = new RepoItemInfo(this, "SignOut", ".//a[@id='HREF_Logout1']", 30000, null, "19fc628a-cad5-447a-a658-df6d99b5d1f1");
                _locnInfo = new RepoItemInfo(this, "Locn", ".//div[@id='wrapper1']//a[@innertext='Locations and Hours']", 30000, null, "a53edab7-3f18-4f98-ae54-c3d32fe46d6b");
                _checkingaccountvariableInfo = new RepoItemInfo(this, "CheckingAccountVariable", ".//div[@id='compare-checking-saving-modal-aco']//div[@class='modal-body eb-modal-body']//buttontag[@id=$CheckingAccountType]", 30000, null, "f52ad2a3-4ac6-43db-b0c7-24ac3b613075");
                _openaccountheadervariableInfo = new RepoItemInfo(this, "OpenAccountHeaderVariable", ".//div[@id='accountOpeningFundAcc']//h1[@innertext=$Title]", 30000, null, "e31c909f-499e-42f6-803f-d84f695edf29");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("53dac7b1-0df7-4c8a-bc5b-6e2657c82d8b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("53dac7b1-0df7-4c8a-bc5b-6e2657c82d8b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InvalidUNorPWError item.
            /// </summary>
            [RepositoryItem("6321f47b-c2d4-43fb-88db-ed6d535b17c2")]
            public virtual Ranorex.DivTag InvalidUNorPWError
            {
                get
                {
                    return _invalidunorpwerrorInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The InvalidUNorPWError item info.
            /// </summary>
            [RepositoryItemInfo("6321f47b-c2d4-43fb-88db-ed6d535b17c2")]
            public virtual RepoItemInfo InvalidUNorPWErrorInfo
            {
                get
                {
                    return _invalidunorpwerrorInfo;
                }
            }

            /// <summary>
            /// The DropdownMenu item.
            /// </summary>
            [RepositoryItem("dfbdcf83-1e6d-4071-b4a5-fea766c3a670")]
            public virtual Ranorex.ImgTag DropdownMenu
            {
                get
                {
                    return _dropdownmenuInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The DropdownMenu item info.
            /// </summary>
            [RepositoryItemInfo("dfbdcf83-1e6d-4071-b4a5-fea766c3a670")]
            public virtual RepoItemInfo DropdownMenuInfo
            {
                get
                {
                    return _dropdownmenuInfo;
                }
            }

            /// <summary>
            /// The SignOut item.
            /// </summary>
            [RepositoryItem("19fc628a-cad5-447a-a658-df6d99b5d1f1")]
            public virtual Ranorex.ATag SignOut
            {
                get
                {
                    return _signoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SignOut item info.
            /// </summary>
            [RepositoryItemInfo("19fc628a-cad5-447a-a658-df6d99b5d1f1")]
            public virtual RepoItemInfo SignOutInfo
            {
                get
                {
                    return _signoutInfo;
                }
            }

            /// <summary>
            /// The Locn item.
            /// </summary>
            [RepositoryItem("a53edab7-3f18-4f98-ae54-c3d32fe46d6b")]
            public virtual Ranorex.ATag Locn
            {
                get
                {
                    return _locnInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Locn item info.
            /// </summary>
            [RepositoryItemInfo("a53edab7-3f18-4f98-ae54-c3d32fe46d6b")]
            public virtual RepoItemInfo LocnInfo
            {
                get
                {
                    return _locnInfo;
                }
            }

            /// <summary>
            /// The CheckingAccountVariable item.
            /// </summary>
            [RepositoryItem("f52ad2a3-4ac6-43db-b0c7-24ac3b613075")]
            public virtual Ranorex.ButtonTag CheckingAccountVariable
            {
                get
                {
                    return _checkingaccountvariableInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The CheckingAccountVariable item info.
            /// </summary>
            [RepositoryItemInfo("f52ad2a3-4ac6-43db-b0c7-24ac3b613075")]
            public virtual RepoItemInfo CheckingAccountVariableInfo
            {
                get
                {
                    return _checkingaccountvariableInfo;
                }
            }

            /// <summary>
            /// The OpenAccountHeaderVariable item.
            /// </summary>
            [RepositoryItem("e31c909f-499e-42f6-803f-d84f695edf29")]
            public virtual Ranorex.H1Tag OpenAccountHeaderVariable
            {
                get
                {
                    return _openaccountheadervariableInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The OpenAccountHeaderVariable item info.
            /// </summary>
            [RepositoryItemInfo("e31c909f-499e-42f6-803f-d84f695edf29")]
            public virtual RepoItemInfo OpenAccountHeaderVariableInfo
            {
                get
                {
                    return _openaccountheadervariableInfo;
                }
            }

            /// <summary>
            /// The SupportPageColMd24 folder.
            /// </summary>
            [RepositoryFolder("fd068e39-bc54-40c3-8859-1aaf8434c394")]
            public virtual SetupAndTeardownRepositoryFolders.SupportPageColMd24Folder SupportPageColMd24
            {
                get { return _supportpagecolmd24; }
            }

            /// <summary>
            /// The LoginModal folder.
            /// </summary>
            [RepositoryFolder("54d0fb94-968e-4252-82b7-b9255e39fcc7")]
            public virtual SetupAndTeardownRepositoryFolders.LoginModalFolder LoginModal
            {
                get { return _loginmodal; }
            }

            /// <summary>
            /// The Footer folder.
            /// </summary>
            [RepositoryFolder("a3e42873-21e3-4bf3-b0e0-13721bbaef5a")]
            public virtual SetupAndTeardownRepositoryFolders.FooterFolder Footer
            {
                get { return _footer; }
            }

            /// <summary>
            /// The WelcomeArea folder.
            /// </summary>
            [RepositoryFolder("3de573a1-2a80-4770-956f-f153642de045")]
            public virtual SetupAndTeardownRepositoryFolders.WelcomeAreaFolder WelcomeArea
            {
                get { return _welcomearea; }
            }

            /// <summary>
            /// The AccountsDashboard folder.
            /// </summary>
            [RepositoryFolder("a86f5879-ca92-4284-a700-9f705f563189")]
            public virtual SetupAndTeardownRepositoryFolders.AccountsDashboardFolder AccountsDashboard
            {
                get { return _accountsdashboard; }
            }
        }

        /// <summary>
        /// The SupportPageColMd24Folder folder.
        /// </summary>
        [RepositoryFolder("fd068e39-bc54-40c3-8859-1aaf8434c394")]
        public partial class SupportPageColMd24Folder : RepoGenBaseFolder
        {
            RepoItemInfo _callusInfo;
            RepoItemInfo _automatedaccountinfoInfo;
            RepoItemInfo _automatedaccountnumberInfo;
            RepoItemInfo _supportnumberInfo;
            RepoItemInfo _onlinebankingsupportheaderInfo;
            RepoItemInfo _businessinquiriesnumberInfo;
            RepoItemInfo _businessinquiriesheaderInfo;
            RepoItemInfo _daysavailableInfo;
            RepoItemInfo _hoursavailableInfo;

            /// <summary>
            /// Creates a new SupportPageColMd24  folder.
            /// </summary>
            public SupportPageColMd24Folder(RepoGenBaseFolder parentFolder) :
                    base("SupportPageColMd24", "body/div[2]", parentFolder, 30000, null, false, "fd068e39-bc54-40c3-8859-1aaf8434c394", "")
            {
                _callusInfo = new RepoItemInfo(this, "CallUs", ".//div[@innertext='Call Us']", 30000, null, "8fdba62a-3fa3-4b00-b343-d18d2d292ae3");
                _automatedaccountinfoInfo = new RepoItemInfo(this, "AutomatedAccountInfo", ".//div[@class='call-us-panel']//div[@innertext='Eastern Bank''s automated account information line is open 24 hours a day, 7 days a week.']", 30000, null, "a369418b-2a4c-4365-9686-ba474ff7e785");
                _automatedaccountnumberInfo = new RepoItemInfo(this, "AutomatedAccountNumber", ".//div[@class='call-us-panel']//div[@innertext='   1-800-EASTERN (327-8376)  ']", 30000, null, "e4d4335b-8935-46ff-873b-6ec293d4281f");
                _supportnumberInfo = new RepoItemInfo(this, "SupportNumber", ".//div[@class='call-us-panel']//a[@innertext='1-800-457-2043']", 30000, null, "3ad16830-f2fa-4c6d-a539-056beaf3d5f7");
                _onlinebankingsupportheaderInfo = new RepoItemInfo(this, "OnlineBankingSupportHeader", ".//div[@class='call-us-panel']//p[@innertext=' Online Banking Support ']", 30000, null, "19c9e5ec-b218-455f-b3e6-dcb9beb92a0f");
                _businessinquiriesnumberInfo = new RepoItemInfo(this, "BusinessInquiriesNumber", ".//div[@class='call-us-panel']//a[@innertext='1-800-333-8000']", 30000, null, "0e2d760a-92ab-49aa-b05c-e09b6207c7e8");
                _businessinquiriesheaderInfo = new RepoItemInfo(this, "BusinessInquiriesHeader", ".//div[@class='call-us-panel']//p[@innertext=' Business Account Inquiries ']", 30000, null, "e11f07bc-3da5-4a4a-bfd3-3a5d22f1f422");
                _daysavailableInfo = new RepoItemInfo(this, "DaysAvailable", ".//div[@class='call-us-panel']//p[@innertext='Mon - Fri ']", 30000, null, "11cdc4a3-6408-43d5-83ef-63638f065c77");
                _hoursavailableInfo = new RepoItemInfo(this, "HoursAvailable", ".//div[@class='call-us-panel']//p/span[@innertext='8:00 AM - 6:00 PM']", 30000, null, "4043f01e-3b05-43c8-ba2b-040e07084d63");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fd068e39-bc54-40c3-8859-1aaf8434c394")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fd068e39-bc54-40c3-8859-1aaf8434c394")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CallUs item.
            /// </summary>
            [RepositoryItem("8fdba62a-3fa3-4b00-b343-d18d2d292ae3")]
            public virtual Ranorex.DivTag CallUs
            {
                get
                {
                    return _callusInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CallUs item info.
            /// </summary>
            [RepositoryItemInfo("8fdba62a-3fa3-4b00-b343-d18d2d292ae3")]
            public virtual RepoItemInfo CallUsInfo
            {
                get
                {
                    return _callusInfo;
                }
            }

            /// <summary>
            /// The AutomatedAccountInfo item.
            /// </summary>
            [RepositoryItem("a369418b-2a4c-4365-9686-ba474ff7e785")]
            public virtual Ranorex.DivTag AutomatedAccountInfo
            {
                get
                {
                    return _automatedaccountinfoInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AutomatedAccountInfo item info.
            /// </summary>
            [RepositoryItemInfo("a369418b-2a4c-4365-9686-ba474ff7e785")]
            public virtual RepoItemInfo AutomatedAccountInfoInfo
            {
                get
                {
                    return _automatedaccountinfoInfo;
                }
            }

            /// <summary>
            /// The AutomatedAccountNumber item.
            /// </summary>
            [RepositoryItem("e4d4335b-8935-46ff-873b-6ec293d4281f")]
            public virtual Ranorex.DivTag AutomatedAccountNumber
            {
                get
                {
                    return _automatedaccountnumberInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AutomatedAccountNumber item info.
            /// </summary>
            [RepositoryItemInfo("e4d4335b-8935-46ff-873b-6ec293d4281f")]
            public virtual RepoItemInfo AutomatedAccountNumberInfo
            {
                get
                {
                    return _automatedaccountnumberInfo;
                }
            }

            /// <summary>
            /// The SupportNumber item.
            /// </summary>
            [RepositoryItem("3ad16830-f2fa-4c6d-a539-056beaf3d5f7")]
            public virtual Ranorex.ATag SupportNumber
            {
                get
                {
                    return _supportnumberInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SupportNumber item info.
            /// </summary>
            [RepositoryItemInfo("3ad16830-f2fa-4c6d-a539-056beaf3d5f7")]
            public virtual RepoItemInfo SupportNumberInfo
            {
                get
                {
                    return _supportnumberInfo;
                }
            }

            /// <summary>
            /// The OnlineBankingSupportHeader item.
            /// </summary>
            [RepositoryItem("19c9e5ec-b218-455f-b3e6-dcb9beb92a0f")]
            public virtual Ranorex.PTag OnlineBankingSupportHeader
            {
                get
                {
                    return _onlinebankingsupportheaderInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The OnlineBankingSupportHeader item info.
            /// </summary>
            [RepositoryItemInfo("19c9e5ec-b218-455f-b3e6-dcb9beb92a0f")]
            public virtual RepoItemInfo OnlineBankingSupportHeaderInfo
            {
                get
                {
                    return _onlinebankingsupportheaderInfo;
                }
            }

            /// <summary>
            /// The BusinessInquiriesNumber item.
            /// </summary>
            [RepositoryItem("0e2d760a-92ab-49aa-b05c-e09b6207c7e8")]
            public virtual Ranorex.ATag BusinessInquiriesNumber
            {
                get
                {
                    return _businessinquiriesnumberInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BusinessInquiriesNumber item info.
            /// </summary>
            [RepositoryItemInfo("0e2d760a-92ab-49aa-b05c-e09b6207c7e8")]
            public virtual RepoItemInfo BusinessInquiriesNumberInfo
            {
                get
                {
                    return _businessinquiriesnumberInfo;
                }
            }

            /// <summary>
            /// The BusinessInquiriesHeader item.
            /// </summary>
            [RepositoryItem("e11f07bc-3da5-4a4a-bfd3-3a5d22f1f422")]
            public virtual Ranorex.PTag BusinessInquiriesHeader
            {
                get
                {
                    return _businessinquiriesheaderInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The BusinessInquiriesHeader item info.
            /// </summary>
            [RepositoryItemInfo("e11f07bc-3da5-4a4a-bfd3-3a5d22f1f422")]
            public virtual RepoItemInfo BusinessInquiriesHeaderInfo
            {
                get
                {
                    return _businessinquiriesheaderInfo;
                }
            }

            /// <summary>
            /// The DaysAvailable item.
            /// </summary>
            [RepositoryItem("11cdc4a3-6408-43d5-83ef-63638f065c77")]
            public virtual Ranorex.PTag DaysAvailable
            {
                get
                {
                    return _daysavailableInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The DaysAvailable item info.
            /// </summary>
            [RepositoryItemInfo("11cdc4a3-6408-43d5-83ef-63638f065c77")]
            public virtual RepoItemInfo DaysAvailableInfo
            {
                get
                {
                    return _daysavailableInfo;
                }
            }

            /// <summary>
            /// The HoursAvailable item.
            /// </summary>
            [RepositoryItem("4043f01e-3b05-43c8-ba2b-040e07084d63")]
            public virtual Ranorex.SpanTag HoursAvailable
            {
                get
                {
                    return _hoursavailableInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The HoursAvailable item info.
            /// </summary>
            [RepositoryItemInfo("4043f01e-3b05-43c8-ba2b-040e07084d63")]
            public virtual RepoItemInfo HoursAvailableInfo
            {
                get
                {
                    return _hoursavailableInfo;
                }
            }
        }

        /// <summary>
        /// The LoginModalFolder folder.
        /// </summary>
        [RepositoryFolder("54d0fb94-968e-4252-82b7-b9255e39fcc7")]
        public partial class LoginModalFolder : RepoGenBaseFolder
        {
            RepoItemInfo _easternbanklogoInfo;
            RepoItemInfo _usernamefieldInfo;
            RepoItemInfo _passwordfieldInfo;
            RepoItemInfo _signinbuttonInfo;
            RepoItemInfo _kjghugytyuyioyuyouiyyuioInfo;

            /// <summary>
            /// Creates a new LoginModal  folder.
            /// </summary>
            public LoginModalFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginModal", ".//div[@id='LoginHDisplay']", parentFolder, 30000, null, false, "54d0fb94-968e-4252-82b7-b9255e39fcc7", "")
            {
                _easternbanklogoInfo = new RepoItemInfo(this, "EasternBankLogo", ".//img[@src~'eastern-bank-consumer-logo.png$']", 30000, null, "00e07eac-876a-4aac-a437-3f438449cc18");
                _usernamefieldInfo = new RepoItemInfo(this, "UsernameField", ".//input[#'AuthenticationFG.USER_PRINCIPAL']", 30000, null, "fa490286-e6d9-4eee-8f2f-66d3ff9cdf54");
                _passwordfieldInfo = new RepoItemInfo(this, "PasswordField", ".//input[#'AuthenticationFG.ACCESS_CODE_1']", 30000, null, "b2f0435a-d283-4011-90b0-3919c04d8565");
                _signinbuttonInfo = new RepoItemInfo(this, "SignInButton", ".//input[#'VALIDATE_CREDENTIALS1']", 30000, null, "f8b47813-b0bb-458f-b567-814fe17e64de");
                _kjghugytyuyioyuyouiyyuioInfo = new RepoItemInfo(this, "kjghugytyuyioyuyouiyyuio", "element", 30000, null, "114068d0-2eb6-4505-99ab-20c75bb31324");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("54d0fb94-968e-4252-82b7-b9255e39fcc7")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("54d0fb94-968e-4252-82b7-b9255e39fcc7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EasternBankLogo item.
            /// </summary>
            [RepositoryItem("00e07eac-876a-4aac-a437-3f438449cc18")]
            public virtual Ranorex.ImgTag EasternBankLogo
            {
                get
                {
                    return _easternbanklogoInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The EasternBankLogo item info.
            /// </summary>
            [RepositoryItemInfo("00e07eac-876a-4aac-a437-3f438449cc18")]
            public virtual RepoItemInfo EasternBankLogoInfo
            {
                get
                {
                    return _easternbanklogoInfo;
                }
            }

            /// <summary>
            /// The UsernameField item.
            /// </summary>
            [RepositoryItem("fa490286-e6d9-4eee-8f2f-66d3ff9cdf54")]
            public virtual Ranorex.InputTag UsernameField
            {
                get
                {
                    return _usernamefieldInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UsernameField item info.
            /// </summary>
            [RepositoryItemInfo("fa490286-e6d9-4eee-8f2f-66d3ff9cdf54")]
            public virtual RepoItemInfo UsernameFieldInfo
            {
                get
                {
                    return _usernamefieldInfo;
                }
            }

            /// <summary>
            /// The PasswordField item.
            /// </summary>
            [RepositoryItem("b2f0435a-d283-4011-90b0-3919c04d8565")]
            public virtual Ranorex.InputTag PasswordField
            {
                get
                {
                    return _passwordfieldInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PasswordField item info.
            /// </summary>
            [RepositoryItemInfo("b2f0435a-d283-4011-90b0-3919c04d8565")]
            public virtual RepoItemInfo PasswordFieldInfo
            {
                get
                {
                    return _passwordfieldInfo;
                }
            }

            /// <summary>
            /// The SignInButton item.
            /// </summary>
            [RepositoryItem("f8b47813-b0bb-458f-b567-814fe17e64de")]
            public virtual Ranorex.InputTag SignInButton
            {
                get
                {
                    return _signinbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SignInButton item info.
            /// </summary>
            [RepositoryItemInfo("f8b47813-b0bb-458f-b567-814fe17e64de")]
            public virtual RepoItemInfo SignInButtonInfo
            {
                get
                {
                    return _signinbuttonInfo;
                }
            }

            /// <summary>
            /// The kjghugytyuyioyuyouiyyuio item.
            /// </summary>
            [RepositoryItem("114068d0-2eb6-4505-99ab-20c75bb31324")]
            public virtual Ranorex.Unknown kjghugytyuyioyuyouiyyuio
            {
                get
                {
                    return _kjghugytyuyioyuyouiyyuioInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The kjghugytyuyioyuyouiyyuio item info.
            /// </summary>
            [RepositoryItemInfo("114068d0-2eb6-4505-99ab-20c75bb31324")]
            public virtual RepoItemInfo kjghugytyuyioyuyouiyyuioInfo
            {
                get
                {
                    return _kjghugytyuyioyuyouiyyuioInfo;
                }
            }
        }

        /// <summary>
        /// The FooterFolder folder.
        /// </summary>
        [RepositoryFolder("a3e42873-21e3-4bf3-b0e0-13721bbaef5a")]
        public partial class FooterFolder : RepoGenBaseFolder
        {
            RepoItemInfo _contactusbuttonInfo;

            /// <summary>
            /// Creates a new Footer  folder.
            /// </summary>
            public FooterFolder(RepoGenBaseFolder parentFolder) :
                    base("Footer", ".//div[@class='footer']", parentFolder, 30000, null, false, "a3e42873-21e3-4bf3-b0e0-13721bbaef5a", "")
            {
                _contactusbuttonInfo = new RepoItemInfo(this, "ContactUsButton", ".//a[@id='PrivacyPolicyfooter3']", 30000, null, "4f319697-479f-4173-85a9-38dfd904a93c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a3e42873-21e3-4bf3-b0e0-13721bbaef5a")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a3e42873-21e3-4bf3-b0e0-13721bbaef5a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContactUsButton item.
            /// </summary>
            [RepositoryItem("4f319697-479f-4173-85a9-38dfd904a93c")]
            public virtual Ranorex.ATag ContactUsButton
            {
                get
                {
                    return _contactusbuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ContactUsButton item info.
            /// </summary>
            [RepositoryItemInfo("4f319697-479f-4173-85a9-38dfd904a93c")]
            public virtual RepoItemInfo ContactUsButtonInfo
            {
                get
                {
                    return _contactusbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The WelcomeAreaFolder folder.
        /// </summary>
        [RepositoryFolder("3de573a1-2a80-4770-956f-f153642de045")]
        public partial class WelcomeAreaFolder : RepoGenBaseFolder
        {
            RepoItemInfo _welcomemessageInfo;
            RepoItemInfo _lastloginInfo;
            RepoItemInfo _searchboxInfo;

            /// <summary>
            /// Creates a new WelcomeArea  folder.
            /// </summary>
            public WelcomeAreaFolder(RepoGenBaseFolder parentFolder) :
                    base("WelcomeArea", ".//div[@class='account-bg']", parentFolder, 30000, null, false, "3de573a1-2a80-4770-956f-f153642de045", "")
            {
                _welcomemessageInfo = new RepoItemInfo(this, "WelcomeMessage", ".//div[@innertext='Welcome!']", 30000, null, "58bec783-fd89-494b-b66b-91d37288742b");
                _lastloginInfo = new RepoItemInfo(this, "LastLogin", ".//div[@innertext~'Last Login.']", 30000, null, "8b77d9cc-fcf2-4f1b-a836-3ad1d5ca8fcc");
                _searchboxInfo = new RepoItemInfo(this, "SearchBox", ".//div[#'accounts-landing-view']//input[@type='text']", 30000, null, "540f9028-ff26-485d-86f4-944bba41692a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3de573a1-2a80-4770-956f-f153642de045")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3de573a1-2a80-4770-956f-f153642de045")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WelcomeMessage item.
            /// </summary>
            [RepositoryItem("58bec783-fd89-494b-b66b-91d37288742b")]
            public virtual Ranorex.DivTag WelcomeMessage
            {
                get
                {
                    return _welcomemessageInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The WelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("58bec783-fd89-494b-b66b-91d37288742b")]
            public virtual RepoItemInfo WelcomeMessageInfo
            {
                get
                {
                    return _welcomemessageInfo;
                }
            }

            /// <summary>
            /// The LastLogin item.
            /// </summary>
            [RepositoryItem("8b77d9cc-fcf2-4f1b-a836-3ad1d5ca8fcc")]
            public virtual Ranorex.DivTag LastLogin
            {
                get
                {
                    return _lastloginInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LastLogin item info.
            /// </summary>
            [RepositoryItemInfo("8b77d9cc-fcf2-4f1b-a836-3ad1d5ca8fcc")]
            public virtual RepoItemInfo LastLoginInfo
            {
                get
                {
                    return _lastloginInfo;
                }
            }

            /// <summary>
            /// The SearchBox item.
            /// </summary>
            [RepositoryItem("540f9028-ff26-485d-86f4-944bba41692a")]
            public virtual Ranorex.InputTag SearchBox
            {
                get
                {
                    return _searchboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SearchBox item info.
            /// </summary>
            [RepositoryItemInfo("540f9028-ff26-485d-86f4-944bba41692a")]
            public virtual RepoItemInfo SearchBoxInfo
            {
                get
                {
                    return _searchboxInfo;
                }
            }
        }

        /// <summary>
        /// The AccountsDashboardFolder folder.
        /// </summary>
        [RepositoryFolder("a86f5879-ca92-4284-a700-9f705f563189")]
        public partial class AccountsDashboardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _searchaccountsinputboxInfo;

            /// <summary>
            /// Creates a new AccountsDashboard  folder.
            /// </summary>
            public AccountsDashboardFolder(RepoGenBaseFolder parentFolder) :
                    base("AccountsDashboard", "", parentFolder, 30000, null, false, "a86f5879-ca92-4284-a700-9f705f563189", "")
            {
                _searchaccountsinputboxInfo = new RepoItemInfo(this, "SearchAccountsInputBox", ".//div[@id='accounts-landing-view']//input[@id='searchInput']", 30000, null, "f43ef598-208d-4b92-88ac-a9b29c589733");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a86f5879-ca92-4284-a700-9f705f563189")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a86f5879-ca92-4284-a700-9f705f563189")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SearchAccountsInputBox item.
            /// </summary>
            [RepositoryItem("f43ef598-208d-4b92-88ac-a9b29c589733")]
            public virtual Ranorex.InputTag SearchAccountsInputBox
            {
                get
                {
                    return _searchaccountsinputboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SearchAccountsInputBox item info.
            /// </summary>
            [RepositoryItemInfo("f43ef598-208d-4b92-88ac-a9b29c589733")]
            public virtual RepoItemInfo SearchAccountsInputBoxInfo
            {
                get
                {
                    return _searchaccountsinputboxInfo;
                }
            }
        }

        /// <summary>
        /// The HomepageEasternBankAppFolder folder.
        /// </summary>
        [RepositoryFolder("7f5a8a12-532e-484a-b43d-f70638e0f8c8")]
        public partial class HomepageEasternBankAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _findabranchoratmnearyouInfo;
            RepoItemInfo _atmbranchlocatorInfo;
            RepoItemInfo _easternbanklogoInfo;

            /// <summary>
            /// Creates a new HomepageEasternBank  folder.
            /// </summary>
            public HomepageEasternBankAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HomepageEasternBank", "/dom[@domain='www.easternbank.com']", parentFolder, 30000, null, false, "7f5a8a12-532e-484a-b43d-f70638e0f8c8", "")
            {
                _findabranchoratmnearyouInfo = new RepoItemInfo(this, "FindABranchOrATMNearYou", ".//div[@id='block-nodetitlebackground']//h1[@innertext='Find a Branch or ATM near you']", 30000, null, "45c73691-978f-4e59-a05f-60dc4916267f");
                _atmbranchlocatorInfo = new RepoItemInfo(this, "ATMBranchLocator", ".//nav[@id='block-header']/ul//a[@innertext='ATM & Branch Locator']", 30000, null, "9448b7be-77d9-479d-85c7-b82bba1c8c51");
                _easternbanklogoInfo = new RepoItemInfo(this, "EasternBankLogo", ".//header[@id='header']//a[@title='Home']/img[@src~'logo.svg$']", 30000, null, "1b4e7e0a-7e24-47ab-9c53-48a4a8ae3e51");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7f5a8a12-532e-484a-b43d-f70638e0f8c8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7f5a8a12-532e-484a-b43d-f70638e0f8c8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FindABranchOrATMNearYou item.
            /// </summary>
            [RepositoryItem("45c73691-978f-4e59-a05f-60dc4916267f")]
            public virtual Ranorex.H1Tag FindABranchOrATMNearYou
            {
                get
                {
                    return _findabranchoratmnearyouInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The FindABranchOrATMNearYou item info.
            /// </summary>
            [RepositoryItemInfo("45c73691-978f-4e59-a05f-60dc4916267f")]
            public virtual RepoItemInfo FindABranchOrATMNearYouInfo
            {
                get
                {
                    return _findabranchoratmnearyouInfo;
                }
            }

            /// <summary>
            /// The ATMBranchLocator item.
            /// </summary>
            [RepositoryItem("9448b7be-77d9-479d-85c7-b82bba1c8c51")]
            public virtual Ranorex.ATag ATMBranchLocator
            {
                get
                {
                    return _atmbranchlocatorInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATMBranchLocator item info.
            /// </summary>
            [RepositoryItemInfo("9448b7be-77d9-479d-85c7-b82bba1c8c51")]
            public virtual RepoItemInfo ATMBranchLocatorInfo
            {
                get
                {
                    return _atmbranchlocatorInfo;
                }
            }

            /// <summary>
            /// The EasternBankLogo item.
            /// </summary>
            [RepositoryItem("1b4e7e0a-7e24-47ab-9c53-48a4a8ae3e51")]
            public virtual Ranorex.ImgTag EasternBankLogo
            {
                get
                {
                    return _easternbanklogoInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The EasternBankLogo item info.
            /// </summary>
            [RepositoryItemInfo("1b4e7e0a-7e24-47ab-9c53-48a4a8ae3e51")]
            public virtual RepoItemInfo EasternBankLogoInfo
            {
                get
                {
                    return _easternbanklogoInfo;
                }
            }
        }

        /// <summary>
        /// The EasternOnlineBankingForgotUserNameAppFolder folder.
        /// </summary>
        [RepositoryFolder("dd7b5f94-36b4-488e-b4d9-c58143ce7b11")]
        public partial class EasternOnlineBankingForgotUserNameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _forgotusernamecancelbuttonInfo;

            /// <summary>
            /// Creates a new EasternOnlineBankingForgotUserName  folder.
            /// </summary>
            public EasternOnlineBankingForgotUserNameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EasternOnlineBankingForgotUserName", "/dom[@caption~'Eastern Online Banking.']", parentFolder, 30000, null, false, "dd7b5f94-36b4-488e-b4d9-c58143ce7b11", "")
            {
                _forgotusernamecancelbuttonInfo = new RepoItemInfo(this, "ForgotUsernameCancelButton", ".//a[#'label_forgot_access_code']", 30000, null, "a4359e37-1db8-4ed7-bf9e-af17d3514f38");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dd7b5f94-36b4-488e-b4d9-c58143ce7b11")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dd7b5f94-36b4-488e-b4d9-c58143ce7b11")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ForgotUsernameCancelButton item.
            /// </summary>
            [RepositoryItem("a4359e37-1db8-4ed7-bf9e-af17d3514f38")]
            public virtual Ranorex.ATag ForgotUsernameCancelButton
            {
                get
                {
                    return _forgotusernamecancelbuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ForgotUsernameCancelButton item info.
            /// </summary>
            [RepositoryItemInfo("a4359e37-1db8-4ed7-bf9e-af17d3514f38")]
            public virtual RepoItemInfo ForgotUsernameCancelButtonInfo
            {
                get
                {
                    return _forgotusernamecancelbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The FirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("f42310c0-0ad1-4206-8690-ec2dc5b493da")]
        public partial class FirefoxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _easternbanktabInfo;

            /// <summary>
            /// Creates a new Firefox  folder.
            /// </summary>
            public FirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Firefox", "/form[@processname='firefox']", parentFolder, 30000, null, true, "f42310c0-0ad1-4206-8690-ec2dc5b493da", "")
            {
                _easternbanktabInfo = new RepoItemInfo(this, "EasternBankTab", "toolbar[@accessiblename='Browser tabs']//tabpage[@accessiblename~'Eastern Online Banking.']", 30000, null, "2ce0a239-1261-4f56-baec-345ecdf64016");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f42310c0-0ad1-4206-8690-ec2dc5b493da")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f42310c0-0ad1-4206-8690-ec2dc5b493da")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EasternBankTab item.
            /// </summary>
            [RepositoryItem("2ce0a239-1261-4f56-baec-345ecdf64016")]
            public virtual Ranorex.TabPage EasternBankTab
            {
                get
                {
                    return _easternbanktabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The EasternBankTab item info.
            /// </summary>
            [RepositoryItemInfo("2ce0a239-1261-4f56-baec-345ecdf64016")]
            public virtual RepoItemInfo EasternBankTabInfo
            {
                get
                {
                    return _easternbanktabInfo;
                }
            }
        }

        /// <summary>
        /// The ChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("825e415e-ae25-4ba0-8cca-5568664c8bd5")]
        public partial class ChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _easternbanktabInfo;

            /// <summary>
            /// Creates a new Chrome  folder.
            /// </summary>
            public ChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Chrome", "/form[@processname='chrome']", parentFolder, 30000, null, true, "825e415e-ae25-4ba0-8cca-5568664c8bd5", "")
            {
                _easternbanktabInfo = new RepoItemInfo(this, "EasternBankTab", ".//tabpagelist[@accessiblerole='PageTabList']//tabpage[@accessiblename~'Eastern.']", 30000, null, "1b581c2c-a94b-4f0e-9373-22d5b6dbded9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("825e415e-ae25-4ba0-8cca-5568664c8bd5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("825e415e-ae25-4ba0-8cca-5568664c8bd5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EasternBankTab item.
            /// </summary>
            [RepositoryItem("1b581c2c-a94b-4f0e-9373-22d5b6dbded9")]
            public virtual Ranorex.TabPage EasternBankTab
            {
                get
                {
                    return _easternbanktabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The EasternBankTab item info.
            /// </summary>
            [RepositoryItemInfo("1b581c2c-a94b-4f0e-9373-22d5b6dbded9")]
            public virtual RepoItemInfo EasternBankTabInfo
            {
                get
                {
                    return _easternbanktabInfo;
                }
            }
        }

        /// <summary>
        /// The IEAppFolder folder.
        /// </summary>
        [RepositoryFolder("fe6f8fa0-931f-4592-97b9-91536e9916a7")]
        public partial class IEAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ietabInfo;

            /// <summary>
            /// Creates a new IE  folder.
            /// </summary>
            public IEAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IE", "/form[@processname='iexplore']", parentFolder, 30000, null, true, "fe6f8fa0-931f-4592-97b9-91536e9916a7", "")
            {
                _ietabInfo = new RepoItemInfo(this, "IETab", ".//container[@class='TabBandClass']//tabpagelist[@accessiblename='Tab Row']//tabpage[@accessiblename~'Eastern.']", 30000, null, "4e16227f-e7ba-4f3a-bcad-8095e0923124");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fe6f8fa0-931f-4592-97b9-91536e9916a7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fe6f8fa0-931f-4592-97b9-91536e9916a7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IETab item.
            /// </summary>
            [RepositoryItem("4e16227f-e7ba-4f3a-bcad-8095e0923124")]
            public virtual Ranorex.TabPage IETab
            {
                get
                {
                    return _ietabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The IETab item info.
            /// </summary>
            [RepositoryItemInfo("4e16227f-e7ba-4f3a-bcad-8095e0923124")]
            public virtual RepoItemInfo IETabInfo
            {
                get
                {
                    return _ietabInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
