///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EasternBankRegression.Module_Recordings.MajorModules.AccountsTab
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AccountHeaderFooter recording.
    /// </summary>
    [TestModule("4734cf60-fc74-4298-971e-5e6d51f11b3f", ModuleType.Recording, 1)]
    public partial class AccountHeaderFooter : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::EasternBankRegression.EasternBankRegressionRepository repository.
        /// </summary>
        public static global::EasternBankRegression.EasternBankRegressionRepository repo = global::EasternBankRegression.EasternBankRegressionRepository.Instance;

        static AccountHeaderFooter instance = new AccountHeaderFooter();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AccountHeaderFooter()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AccountHeaderFooter Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(0));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'EasternOnlineBankingDashboard.Accounts1'.", repo.EasternOnlineBankingDashboard.Accounts1Info, new RecordItemIndex(1));
            repo.EasternOnlineBankingDashboard.Accounts1.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.WelcomeMessage'", repo.EasternOnlineBankingDashboard.WelcomeMessageInfo, new RecordItemIndex(2));
            repo.EasternOnlineBankingDashboard.WelcomeMessageInfo.WaitForAttributeEqual(60000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.EasternBankLogo1'.", repo.EasternOnlineBankingDashboard.EasternBankLogo1Info, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.EasternBankLogo1Info, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.Accounts2'.", repo.EasternOnlineBankingDashboard.Accounts2Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.Accounts2Info, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.Transfers3'.", repo.EasternOnlineBankingDashboard.Transfers3Info, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.Transfers3Info, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.BillPay1'.", repo.EasternOnlineBankingDashboard.BillPay1Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.BillPay1Info, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.DebitCards'.", repo.EasternOnlineBankingDashboard.DebitCardsInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.DebitCardsInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.Settings'.", repo.EasternOnlineBankingDashboard.SettingsInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.SettingsInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.Support1'.", repo.EasternOnlineBankingDashboard.Support1Info, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.Support1Info, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Valid='True') on item 'EasternOnlineBankingDashboard.Messages'.", repo.EasternOnlineBankingDashboard.MessagesInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.MessagesInfo, "Valid", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.Feedback'.", repo.EasternOnlineBankingDashboard.FeedbackInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.FeedbackInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.TopRightName'.", repo.EasternOnlineBankingDashboard.TopRightNameInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.TopRightNameInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'EasternOnlineBankingDashboard.EqualHousingLenderSprite'.", repo.EasternOnlineBankingDashboard.EqualHousingLenderSpriteInfo, new RecordItemIndex(13));
            Validate.Exists(repo.EasternOnlineBankingDashboard.EqualHousingLenderSpriteInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'EasternOnlineBankingDashboard.EqualHousingLender'.", repo.EasternOnlineBankingDashboard.EqualHousingLenderInfo, new RecordItemIndex(14));
            Validate.Exists(repo.EasternOnlineBankingDashboard.EqualHousingLenderInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'EasternOnlineBankingDashboard.MemberFDIC'.", repo.EasternOnlineBankingDashboard.MemberFDICInfo, new RecordItemIndex(15));
            Validate.Exists(repo.EasternOnlineBankingDashboard.MemberFDICInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'EasternOnlineBankingDashboard.PrivacyPolicy'.", repo.EasternOnlineBankingDashboard.PrivacyPolicyInfo, new RecordItemIndex(16));
            Validate.Exists(repo.EasternOnlineBankingDashboard.PrivacyPolicyInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'EasternOnlineBankingDashboard.Agreement'.", repo.EasternOnlineBankingDashboard.AgreementInfo, new RecordItemIndex(17));
            Validate.Exists(repo.EasternOnlineBankingDashboard.AgreementInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'EasternOnlineBankingDashboard.ESignConsent'.", repo.EasternOnlineBankingDashboard.ESignConsentInfo, new RecordItemIndex(18));
            Validate.Exists(repo.EasternOnlineBankingDashboard.ESignConsentInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'EasternOnlineBankingDashboard.FeeSchedule'.", repo.EasternOnlineBankingDashboard.FeeScheduleInfo, new RecordItemIndex(19));
            Validate.Exists(repo.EasternOnlineBankingDashboard.FeeScheduleInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'EasternOnlineBankingDashboard.CopyrightAllRightsReserved'.", repo.EasternOnlineBankingDashboard.CopyrightAllRightsReservedInfo, new RecordItemIndex(20));
            Validate.Exists(repo.EasternOnlineBankingDashboard.CopyrightAllRightsReservedInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
