///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace BillPayReports
{
    public partial class SelectBillPayReportTab
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Invoke_action_SelectReportDropdown(RepoItemInfo divtagInfo)
        {
            var repo = BillPayReportsRepository.Instance;
            var selectReportDropdown = repo.EasternOnlineBankingBillPay.ReportsTabPage.SelectReportDropdown;

            selectReportDropdown.Self.PerformClick();
            Delay.Milliseconds(500);
            var reportcont = repo.EasternOnlineBankingBillPay.ReportsTabPage.BillPayReportsList.NonDefaultReports;

            
            
            while (repo.EasternOnlineBankingBillPay.ReportsTabPage.BillPayReportsList.NonDefaultReportsInfo.Exists()) {
            	IList<Ranorex.SpanTag> list = repo.EasternOnlineBankingBillPay.ReportsTabPage.BillPayReportsList.NonDefaultReportsInfo.CreateAdapters<Ranorex.SpanTag>();
            	int num = list.Count;
            	Report.Info("there are "+num.ToString()+"  reports to be deleted");
            	
            	foreach (Ranorex.SpanTag item in list) {
            		string name = item.Element.GetAttributeValueText("innertext").ToString();
            		DivTag someDivTag = "/dom[@domain='fnclmobqa.easternbank.com:8543']//div[#'defReportBill']/div[@class~'accounts']//span[@innertext='"+name+"']/..";
            		someDivTag.Click();
            		var billPayReportLoadingModal = repo.EasternOnlineBankingBillPay.BillPayReportLoadingModal;
            		repo.EasternOnlineBankingBillPay.BillPayReportLoadingModalInfo.WaitForAttributeEqual(30000,"Visible","False");
            		var deleteButton = repo.EasternOnlineBankingBillPay.ReportsTabPage.DeleteButton;
            		deleteButton.PerformClick();
            		var yesButton = repo.EasternOnlineBankingBillPay.AreYouSureYouWantToDeleteReportModal.YesButton;
            		yesButton.Click();
            		repo.EasternOnlineBankingBillPay.BillPayReportLoadingModalInfo.WaitForAttributeEqual(30000,"Visible","True");
            		var deleteReportSuccessModal = repo.EasternOnlineBankingBillPay.DeleteReportSuccessModal;
            		repo.EasternOnlineBankingBillPay.DeleteReportSuccessModal.SelfInfo.WaitForAttributeEqual(30000,"Visible","True");
            		repo.EasternOnlineBankingBillPay.BillPayReportLoadingModalInfo.WaitForAttributeEqual(30000,"Visible","False");
            		var doneButton = repo.EasternOnlineBankingBillPay.DeleteReportSuccessModal.DoneButton;
            		num --;
            		Report.Info(num.ToString());
            		doneButton.PerformClick();
            		Delay.Seconds(1);
            		selectReportDropdown.Self.PerformClick();
            		if (num == 0) {
            			Report.Info("no saved reports exists");
            			selectReportDropdown.Self.PerformClick();
            			break;
            		}

            	}
            }
            if (!repo.EasternOnlineBankingBillPay.ReportsTabPage.BillPayReportsList.NonDefaultReportsInfo.Exists()) {
            	Report.Info("no saved reports exists");
            	selectReportDropdown.Self.PerformClick();
            	Delay.Seconds(1);
            }
        }

    }
}
