///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NewAccountOpening
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AccountOpenSuccessModalValidation recording.
    /// </summary>
    [TestModule("4a24aacd-645b-4cbf-af23-16a30504a384", ModuleType.Recording, 1)]
    public partial class AccountOpenSuccessModalValidation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NewAccountOpeningRepository repository.
        /// </summary>
        public static NewAccountOpeningRepository repo = NewAccountOpeningRepository.Instance;

        static AccountOpenSuccessModalValidation instance = new AccountOpenSuccessModalValidation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AccountOpenSuccessModalValidation()
        {
            OpeningDeposit = "$500.00";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AccountOpenSuccessModalValidation Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable OpenSuccessMessage.
        /// </summary>
        [TestVariable("310116ad-8abb-48cd-b4b8-3cf33a804f03")]
        public string OpenSuccessMessage
        {
            get { return repo.OpenSuccessMessage; }
            set { repo.OpenSuccessMessage = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable OpeningDeposit.
        /// </summary>
        [TestVariable("da642fff-a51a-4290-93d5-a2cb35b19a63")]
        public string OpeningDeposit
        {
            get { return repo.OpeningDeposit; }
            set { repo.OpeningDeposit = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'EasternOnlineBankingDashboard.SuccessModal.VariableAccountHasBeenOpenedHeader'", repo.EasternOnlineBankingDashboard.SuccessModal.VariableAccountHasBeenOpenedHeaderInfo, new RecordItemIndex(0));
            repo.EasternOnlineBankingDashboard.SuccessModal.VariableAccountHasBeenOpenedHeaderInfo.WaitForAttributeEqual(60000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.SuccessModal.YourNewAccountNumberIs'.", repo.EasternOnlineBankingDashboard.SuccessModal.YourNewAccountNumberIsInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.SuccessModal.YourNewAccountNumberIsInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.SuccessModal.AccountOwner'.", repo.EasternOnlineBankingDashboard.SuccessModal.AccountOwnerInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.SuccessModal.AccountOwnerInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.SuccessModal.OpeningDepositVariable'.", repo.EasternOnlineBankingDashboard.SuccessModal.OpeningDepositVariableInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.SuccessModal.OpeningDepositVariableInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.SuccessModal.DateOpened'.", repo.EasternOnlineBankingDashboard.SuccessModal.DateOpenedInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.SuccessModal.DateOpenedInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EasternOnlineBankingDashboard.DoneButton'.", repo.EasternOnlineBankingDashboard.DoneButtonInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.EasternOnlineBankingDashboard.DoneButtonInfo, "Visible", "True");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
